// Seed-cache book list, part 1/4 (split for deploy-transport size limits — see novelviz-feedback-deploy-edge-function-size-limit memory).
export const BOOKS_1: string[] = [
  // ── Self-help / Psychology / Productivity ──────────────────────────────────
  "Sapiens by Yuval Noah Harari",
  "Homo Deus by Yuval Noah Harari",
  "21 Lessons for the 21st Century by Yuval Noah Harari",
  "Thinking, Fast and Slow by Daniel Kahneman",
  "Atomic Habits by James Clear",
  "The Power of Now by Eckhart Tolle",
  "Man's Search for Meaning by Viktor Frankl",
  "The Subtle Art of Not Giving a F*ck by Mark Manson",
  "Everything Is F*cked by Mark Manson",
  "Quiet by Susan Cain",
  "Daring Greatly by Brené Brown",
  "The Gifts of Imperfection by Brené Brown",
  "Braving the Wilderness by Brené Brown",
  "Atlas of the Heart by Brené Brown",
  "Deep Work by Cal Newport",
  "Digital Minimalism by Cal Newport",
  "So Good They Can't Ignore You by Cal Newport",
  "A World Without Email by Cal Newport",
  "Slow Productivity by Cal Newport",
  "Start With Why by Simon Sinek",
  "Leaders Eat Last by Simon Sinek",
  "The Infinite Game by Simon Sinek",
  "Find Your Why by Simon Sinek",
  "The Body Keeps the Score by Bessel van der Kolk",
  "Why We Sleep by Matthew Walker",
  "Lifespan by David Sinclair",
  "The Anxious Generation by Jonathan Haidt",
  "The Coddling of the American Mind by Jonathan Haidt",
  "The Righteous Mind by Jonathan Haidt",
  "Flow by Mihaly Csikszentmihalyi",
  "Grit by Angela Duckworth",
  "Mindset by Carol S. Dweck",
  "Drive by Daniel H. Pink",
  "A Whole New Mind by Daniel H. Pink",
  "When by Daniel H. Pink",
  "The Power of Habit by Charles Duhigg",
  "Smarter Faster Better by Charles Duhigg",
  "Stumbling on Happiness by Daniel Gilbert",
  "Predictably Irrational by Dan Ariely",
  "The Paradox of Choice by Barry Schwartz",
  "Switch by Chip Heath and Dan Heath",
  "Made to Stick by Chip Heath and Dan Heath",
  "Decisive by Chip Heath and Dan Heath",
  "The War of Art by Steven Pressfield",
  "Big Magic by Elizabeth Gilbert",
  "Eat Pray Love by Elizabeth Gilbert",
  "The Artist's Way by Julia Cameron",
  "How to Win Friends and Influence People by Dale Carnegie",
  "How to Stop Worrying and Start Living by Dale Carnegie",
  "Never Split the Difference by Chris Voss",
  "Getting to Yes by Roger Fisher",
  "Influence by Robert Cialdini",
  "Pre-Suasion by Robert Cialdini",
  "Crucial Conversations by Kerry Patterson",
  "The 7 Habits of Highly Effective People by Stephen Covey",
  "First Things First by Stephen Covey",
  "The 4-Hour Workweek by Tim Ferriss",
  "Tools of Titans by Tim Ferriss",
  "Tribe of Mentors by Tim Ferriss",
  "Essentialism by Greg McKeown",
  "Effortless by Greg McKeown",
  "The One Thing by Gary Keller",
  "Getting Things Done by David Allen",
  "Your Money or Your Life by Vicki Robin",
  "The Total Money Makeover by Dave Ramsey",
  "I Will Teach You to Be Rich by Ramit Sethi",
  "The Millionaire Next Door by Thomas J. Stanley",
  "A Random Walk Down Wall Street by Burton Malkiel",
  "The Psychology of Money by Morgan Housel",
  "Same as Ever by Morgan Housel",
  "Rich Dad Poor Dad by Robert Kiyosaki",
  "Think and Grow Rich by Napoleon Hill",
  "The Science of Getting Rich by Wallace D. Wattles",
  "The Richest Man in Babylon by George S. Clason",
  "Die With Zero by Bill Perkins",
  "Set Boundaries, Find Peace by Nedra Glennon Tawwab",
  "The Four Agreements by Don Miguel Ruiz",
  "The Fifth Agreement by Don Miguel Ruiz",
  "The Untethered Soul by Michael A. Singer",
  "The Surrender Experiment by Michael A. Singer",
  "Letting Go by David R. Hawkins",
  "Lost Connections by Johann Hari",
  "Stolen Focus by Johann Hari",
  "Chatter by Ethan Kross",
  "Think Again by Adam Grant",
  "Give and Take by Adam Grant",
  "Originals by Adam Grant",
  "Hidden Potential by Adam Grant",
  "Attached by Amir Levine and Rachel Heller",
  "The Seven Principles for Making Marriage Work by John Gottman",
  "Hold Me Tight by Sue Johnson",
  "Adult Children of Emotionally Immature Parents by Lindsay C. Gibson",
  "It Didn't Start with You by Mark Wolynn",
  "What Happened to You by Bruce D. Perry and Oprah Winfrey",
  "Complex PTSD by Pete Walker",
  "The Drama of the Gifted Child by Alice Miller",
  "Nonviolent Communication by Marshall B. Rosenberg",
  "The Road Less Travelled by M. Scott Peck",
  "When Things Fall Apart by Pema Chödrön",
  "Start Where You Are by Pema Chödrön",
  "Wherever You Go, There You Are by Jon Kabat-Zinn",
  "Full Catastrophe Living by Jon Kabat-Zinn",
  "The Miracle of Mindfulness by Thich Nhat Hanh",
  "No Mud, No Lotus by Thich Nhat Hanh",
  "Siddhartha by Hermann Hesse",
  "Steppenwolf by Hermann Hesse",
  "Demian by Hermann Hesse",
  "Be Here Now by Ram Dass",
  "A New Earth by Eckhart Tolle",

  // ── Business / Leadership / Entrepreneurship ───────────────────────────────
  "Zero to One by Peter Thiel",
  "The Hard Thing About Hard Things by Ben Horowitz",
  "Good to Great by Jim Collins",
  "Built to Last by Jim Collins",
  "Great by Choice by Jim Collins",
  "The Lean Startup by Eric Ries",
  "Rework by Jason Fried and David Heinemeier Hansson",
  "Remote by Jason Fried and David Heinemeier Hansson",
  "It Doesn't Have to Be Crazy at Work by Jason Fried and David Heinemeier Hansson",
  "The E-Myth Revisited by Michael E. Gerber",
  "Thinking in Bets by Annie Duke",
  "Principles by Ray Dalio",
  "Principles for Dealing with the Changing World Order by Ray Dalio",
  "The Innovator's Dilemma by Clayton M. Christensen",
  "The Innovator's Solution by Clayton M. Christensen",
  "Competing Against Luck by Clayton M. Christensen",
  "Crossing the Chasm by Geoffrey A. Moore",
  "Blue Ocean Strategy by W. Chan Kim and Renée Mauborgne",
  "Measure What Matters by John Doerr",
  "High Output Management by Andrew S. Grove",
  "Only the Paranoid Survive by Andrew S. Grove",
  "The Effective Executive by Peter F. Drucker",
  "Shoe Dog by Phil Knight",
  "Losing My Virginity by Richard Branson",
  "Pour Your Heart Into It by Howard Schultz",
  "Bad Blood by John Carreyrou",
  "Super Pumped by Mike Isaac",
  "No Filter by Sarah Frier",
  "The Everything Store by Brad Stone",
  "Invent and Wander by Jeff Bezos",
  "Creativity, Inc. by Ed Catmull",
  "Hit Refresh by Satya Nadella",
  "No Rules Rules by Reed Hastings and Erin Meyer",
  "The Culture Code by Daniel Coyle",
  "Trillion Dollar Coach by Eric Schmidt",
  "The Age of Surveillance Capitalism by Shoshana Zuboff",
  "The Cold Start Problem by Andrew Chen",
  "Blitzscaling by Reid Hoffman",
  "The Lean Product Playbook by Dan Olsen",
  "Continuous Discovery Habits by Teresa Torres",
  "Inspired by Marty Cagan",
  "Empowered by Marty Cagan",
  "Transformed by Marty Cagan",
  "Obviously Awesome by April Dunford",
  "The Mom Test by Rob Fitzpatrick",
  "Traction by Gabriel Weinberg and Justin Mares",
  "$100M Offers by Alex Hormozi",
  "$100M Leads by Alex Hormozi",
  "Building a StoryBrand by Donald Miller",
  "Contagious by Jonah Berger",
  "This Is Marketing by Seth Godin",
  "Linchpin by Seth Godin",
  "Purple Cow by Seth Godin",
  "Tribes by Seth Godin",
  "The Dip by Seth Godin",

  // ── History / Politics / Society ───────────────────────────────────────────
  "Guns, Germs, and Steel by Jared Diamond",
  "Collapse by Jared Diamond",
  "The Rise and Fall of the Third Reich by William L. Shirer",
  "Team of Rivals by Doris Kearns Goodwin",
  "The Warmth of Other Suns by Isabel Wilkerson",
  "Caste by Isabel Wilkerson",
  "Between the World and Me by Ta-Nehisi Coates",
  "Just Mercy by Bryan Stevenson",
  "The New Jim Crow by Michelle Alexander",
  "How to Be an Antiracist by Ibram X. Kendi",
  "Stamped from the Beginning by Ibram X. Kendi",
  "A People's History of the United States by Howard Zinn",
  "Evicted by Matthew Desmond",
  "Poverty, by America by Matthew Desmond",
  "Nickel and Dimed by Barbara Ehrenreich",
  "Capital in the Twenty-First Century by Thomas Piketty",
  "The Road to Serfdom by Friedrich Hayek",
  "The Origins of Totalitarianism by Hannah Arendt",
  "Eichmann in Jerusalem by Hannah Arendt",
  "On Tyranny by Timothy Snyder",
  "The Road to Unfreedom by Timothy Snyder",
  "Bloodlands by Timothy Snyder",
  "Ordinary Men by Christopher R. Browning",
  "Night by Elie Wiesel",
  "Maus by Art Spiegelman",
  "The Diary of a Young Girl by Anne Frank",
  "Postwar by Tony Judt",
  "The Lessons of History by Will Durant and Ariel Durant",
  "SPQR by Mary Beard",
  "Rubicon by Tom Holland",
  "Dominion by Tom Holland",
  "The Silk Roads by Peter Frankopan",
  "The Anarchy by William Dalrymple",
  "The Guns of August by Barbara Tuchman",
  "A Distant Mirror by Barbara Tuchman",
  "Churchill by Andrew Roberts",
  "Napoleon by Andrew Roberts",
  "The Second World War by Antony Beevor",
  "Stalingrad by Antony Beevor",
  "D-Day by Antony Beevor",
  "The Gulag Archipelago by Aleksandr Solzhenitsyn",
  "Mao's Great Famine by Frank Dikötter",
  "The Art of War by Sun Tzu",
  "The Prince by Niccolò Machiavelli",

  // ── Science / Technology / Ideas ───────────────────────────────────────────
  "A Brief History of Time by Stephen Hawking",
  "The Grand Design by Stephen Hawking",
  "The Selfish Gene by Richard Dawkins",
  "The God Delusion by Richard Dawkins",
  "The Blind Watchmaker by Richard Dawkins",
  "On the Origin of Species by Charles Darwin",
  "The Double Helix by James D. Watson",
  "The Gene by Siddhartha Mukherjee",
  "The Emperor of All Maladies by Siddhartha Mukherjee",
  "Being Mortal by Atul Gawande",
  "The Checklist Manifesto by Atul Gawande",
  "The Brain That Changes Itself by Norman Doidge",
  "The Man Who Mistook His Wife for a Hat by Oliver Sacks",
  "Surely You're Joking, Mr. Feynman by Richard P. Feynman",
  "The Elegant Universe by Brian Greene",
  "The Fabric of the Cosmos by Brian Greene",
  "Cosmos by Carl Sagan",
  "The Demon-Haunted World by Carl Sagan",
  "Pale Blue Dot by Carl Sagan",
  "Astrophysics for People in a Hurry by Neil deGrasse Tyson",
  "The Information by James Gleick",
  "Chaos by James Gleick",
  "The Structure of Scientific Revolutions by Thomas S. Kuhn",
  "Gödel, Escher, Bach by Douglas R. Hofstadter",
  "The Language Instinct by Steven Pinker",
  "The Blank Slate by Steven Pinker",
  "Enlightenment Now by Steven Pinker",
  "The Better Angels of Our Nature by Steven Pinker",
  "Noise by Daniel Kahneman",
  "The Innovators by Walter Isaacson",
  "Steve Jobs by Walter Isaacson",
  "Elon Musk by Walter Isaacson",
  "Leonardo da Vinci by Walter Isaacson",
  "Einstein by Walter Isaacson",
  "The Shallows by Nicholas Carr",
  "You Are Not a Gadget by Jaron Lanier",
  "The Second Machine Age by Erik Brynjolfsson and Andrew McAfee",
  "Life 3.0 by Max Tegmark",
  "Superintelligence by Nick Bostrom",
  "Human Compatible by Stuart Russell",
  "Weapons of Math Destruction by Cathy O'Neil",
  "The Alignment Problem by Brian Christian",
  "The Coming Wave by Mustafa Suleyman",
  "Co-Intelligence by Ethan Mollick",
  "A Crack in Creation by Jennifer Doudna",
  "Behave by Robert M. Sapolsky",
  "Why Zebras Don't Get Ulcers by Robert M. Sapolsky",
  "Determined by Robert M. Sapolsky",
  "The Sixth Extinction by Elizabeth Kolbert",
  "The Uninhabitable Earth by David Wallace-Wells",
  "This Changes Everything by Naomi Klein",
  "Silent Spring by Rachel Carson",
  "Braiding Sweetgrass by Robin Wall Kimmerer",
  "The Hidden Life of Trees by Peter Wohlleben",
  "Finding the Mother Tree by Suzanne Simard",
  "The Botany of Desire by Michael Pollan",
  "In Defence of Food by Michael Pollan",
  "The Omnivore's Dilemma by Michael Pollan",
  "How to Change Your Mind by Michael Pollan",
  "Freakonomics by Steven D. Levitt and Stephen J. Dubner",
  "SuperFreakonomics by Steven D. Levitt and Stephen J. Dubner",
  "Misbehaving by Richard Thaler",
  "Nudge by Richard Thaler and Cass Sunstein",
  "The Black Swan by Nassim Nicholas Taleb",
  "Fooled by Randomness by Nassim Nicholas Taleb",
  "Antifragile by Nassim Nicholas Taleb",
  "Skin in the Game by Nassim Nicholas Taleb",

  // ── Biography / Memoir ─────────────────────────────────────────────────────
  "Educated by Tara Westover",
  "Becoming by Michelle Obama",
  "The Light We Carry by Michelle Obama",
  "A Promised Land by Barack Obama",
  "Dreams from My Father by Barack Obama",
  "Long Walk to Freedom by Nelson Mandela",
  "I Know Why the Caged Bird Sings by Maya Angelou",
  "When Breath Becomes Air by Paul Kalanithi",
  "The Year of Magical Thinking by Joan Didion",
  "Lab Girl by Hope Jahren",
  "Born a Crime by Trevor Noah",
  "The Glass Castle by Jeannette Walls",
  "Americanah by Chimamanda Ngozi Adichie",
  "We Should All Be Feminists by Chimamanda Ngozi Adichie",
  "A Long Way Gone by Ishmael Beah",
  "Persepolis by Marjane Satrapi",
  // "Maus by Art Spiegelman" already listed above (History/Politics/Society,
  // pre-existing dup found 2026-07-22) — removed here, not re-added.
  "Fun Home by Alison Bechdel",
  "The Autobiography of Malcolm X by Malcolm X",
  "Wild by Cheryl Strayed",
  "Tiny Beautiful Things by Cheryl Strayed",
  "A Walk in the Woods by Bill Bryson",
  "In a Sunburned Country by Bill Bryson",
  "Notes from a Small Island by Bill Bryson",
  "A Short History of Nearly Everything by Bill Bryson",
  "The Body by Bill Bryson",
  "Into the Wild by Jon Krakauer",
  "Into Thin Air by Jon Krakauer",
  "Under the Banner of Heaven by Jon Krakauer",
  "Endurance by Alfred Lansing",
  "Unbroken by Laura Hillenbrand",
  "Seabiscuit by Laura Hillenbrand",
  "The Immortal Life of Henrietta Lacks by Rebecca Skloot",
  "Devil in the White City by Erik Larson",
  "Dead Wake by Erik Larson",
  "In the Garden of Beasts by Erik Larson",
  "Say Nothing by Patrick Radden Keefe",
  "Empire of Pain by Patrick Radden Keefe",
  "Columbine by Dave Cullen",
  "I'll Be Gone in the Dark by Michelle McNamara",
  "Killers of the Flower Moon by David Grann",
  "The Wager by David Grann",
  "The Lost City of Z by David Grann",
  "The Radium Girls by Kate Moore",
  "I'm Glad My Mom Died by Jennette McCurdy",
  "Greenlights by Matthew McConaughey",
  "Spare by Prince Harry",
  "Finding Me by Viola Davis",
  "Open by Andre Agassi",
  "Unreasonable Hospitality by Will Guidara",

  // ── Philosophy / Classics ──────────────────────────────────────────────────
  "Meditations by Marcus Aurelius",
  "Letters from a Stoic by Seneca",
  "On the Shortness of Life by Seneca",
  "Discourses by Epictetus",
  "The Enchiridion by Epictetus",
  "Nicomachean Ethics by Aristotle",
  "The Republic by Plato",
  "Symposium by Plato",
  "Thus Spoke Zarathustra by Friedrich Nietzsche",
  "Beyond Good and Evil by Friedrich Nietzsche",
  "On the Genealogy of Morality by Friedrich Nietzsche",
  "The Gay Science by Friedrich Nietzsche",
  "Being and Nothingness by Jean-Paul Sartre",
  "Nausea by Jean-Paul Sartre",
  "The Second Sex by Simone de Beauvoir",
  "The Ethics of Ambiguity by Simone de Beauvoir",
  "The Myth of Sisyphus by Albert Camus",
  "The Rebel by Albert Camus",
  "Critique of Pure Reason by Immanuel Kant",
  "Groundwork of the Metaphysics of Morals by Immanuel Kant",
  "The Communist Manifesto by Karl Marx",
  "The Wealth of Nations by Adam Smith",
  "Leviathan by Thomas Hobbes",
  "Two Treatises of Government by John Locke",
  "A Treatise of Human Nature by David Hume",
  "The Social Contract by Jean-Jacques Rousseau",
  "On Liberty by John Stuart Mill",
  "Utilitarianism by John Stuart Mill",
  "Fear and Trembling by Søren Kierkegaard",
  "The World as Will and Representation by Arthur Schopenhauer",
  "Essays and Aphorisms by Arthur Schopenhauer",
  "A Theory of Justice by John Rawls",
  "The Obstacle Is the Way by Ryan Holiday",
  "Ego Is the Enemy by Ryan Holiday",
  "The Daily Stoic by Ryan Holiday",
  "Stillness Is the Key by Ryan Holiday",
  "Courage Is Calling by Ryan Holiday",
  "Discipline Is Destiny by Ryan Holiday",
  "The 48 Laws of Power by Robert Greene",
  "Mastery by Robert Greene",
  "The Laws of Human Nature by Robert Greene",
  "The Art of Seduction by Robert Greene",
  "The 33 Strategies of War by Robert Greene",

  // ── Literary Fiction – American ────────────────────────────────────────────
  "To Kill a Mockingbird by Harper Lee",
  "1984 by George Orwell",
  "Animal Farm by George Orwell",
  "Brave New World by Aldous Huxley",
  "The Great Gatsby by F. Scott Fitzgerald",
  "Tender Is the Night by F. Scott Fitzgerald",
  "Of Mice and Men by John Steinbeck",
  "The Grapes of Wrath by John Steinbeck",
  "East of Eden by John Steinbeck",
  "Cannery Row by John Steinbeck",
  "The Catcher in the Rye by J.D. Salinger",
  "Franny and Zooey by J.D. Salinger",
  "The Old Man and the Sea by Ernest Hemingway",
  "A Farewell to Arms by Ernest Hemingway",
  "For Whom the Bell Tolls by Ernest Hemingway",
  "The Sun Also Rises by Ernest Hemingway",
  "A Moveable Feast by Ernest Hemingway",
  "Moby Dick by Herman Melville",
  "The Scarlet Letter by Nathaniel Hawthorne",
  "Adventures of Huckleberry Finn by Mark Twain",
  "The Adventures of Tom Sawyer by Mark Twain",
  "The Road by Cormac McCarthy",
  "Blood Meridian by Cormac McCarthy",
  "No Country for Old Men by Cormac McCarthy",
  "All the Pretty Horses by Cormac McCarthy",
  "The Passenger by Cormac McCarthy",
  "Normal People by Sally Rooney",
  "Conversations with Friends by Sally Rooney",
  "Beautiful World, Where Are You by Sally Rooney",
  "Intermezzo by Sally Rooney",
  "A Little Life by Hanya Yanagihara",
  "The People in the Trees by Hanya Yanagihara",
  "To Paradise by Hanya Yanagihara",
  "The Sympathizer by Viet Thanh Nguyen",
  "The Committed by Viet Thanh Nguyen",
  "Lincoln in the Bardo by George Saunders",
  "Tenth of December by George Saunders",
  "Fleishman Is in Trouble by Taffy Brodesser-Akner",
  "Pachinko by Min Jin Lee",
  "White Noise by Don DeLillo",
  "Underworld by Don DeLillo",
  "Libra by Don DeLillo",
  "Infinite Jest by David Foster Wallace",
  "The Pale King by David Foster Wallace",
  "The Corrections by Jonathan Franzen",
  "Freedom by Jonathan Franzen",
  "Purity by Jonathan Franzen",
  "Crossroads by Jonathan Franzen",
  "Gilead by Marilynne Robinson",
  "Housekeeping by Marilynne Robinson",
  "Home by Marilynne Robinson",
  "Lila by Marilynne Robinson",
  "Beloved by Toni Morrison",
  "Song of Solomon by Toni Morrison",
  "Sula by Toni Morrison",
  "The Bluest Eye by Toni Morrison",
  "Jazz by Toni Morrison",
  "Their Eyes Were Watching God by Zora Neale Hurston",
  "Invisible Man by Ralph Ellison",
  "The Color Purple by Alice Walker",
  "Go Tell It on the Mountain by James Baldwin",
  "Giovanni's Room by James Baldwin",
  "Another Country by James Baldwin",
  "The Fire Next Time by James Baldwin",
  "If Beale Street Could Talk by James Baldwin",
  "Kindred by Octavia Butler",
  "Parable of the Sower by Octavia Butler",
  "Parable of the Talents by Octavia Butler",
  "The Crying of Lot 49 by Thomas Pynchon",
  "Gravity's Rainbow by Thomas Pynchon",
  "My Year of Rest and Relaxation by Ottessa Moshfegh",
  "Eileen by Ottessa Moshfegh",
  "Lapvona by Ottessa Moshfegh",
  "A Visit from the Goon Squad by Jennifer Egan",
  "The Virgin Suicides by Jeffrey Eugenides",
  "Middlesex by Jeffrey Eugenides",
  "The Marriage Plot by Jeffrey Eugenides",
  "American Pastoral by Philip Roth",
  "The Human Stain by Philip Roth",
  "Sabbath's Theater by Philip Roth",
  "Portnoy's Complaint by Philip Roth",
  "The Plot Against America by Philip Roth",
  "The Bell Jar by Sylvia Plath",
  "On the Road by Jack Kerouac",
  "The Dharma Bums by Jack Kerouac",
  "A Streetcar Named Desire by Tennessee Williams",
  "The Glass Menagerie by Tennessee Williams",
  "Death of a Salesman by Arthur Miller",
  "The Crucible by Arthur Miller",
  "Catch-22 by Joseph Heller",
  "Something Happened by Joseph Heller",
  "Slaughterhouse-Five by Kurt Vonnegut",
  "Cat's Cradle by Kurt Vonnegut",
  "Breakfast of Champions by Kurt Vonnegut",
  "Mother Night by Kurt Vonnegut",
  "One Flew Over the Cuckoo's Nest by Ken Kesey",
  "The Adventures of Augie March by Saul Bellow",
  "Herzog by Saul Bellow",
  "Henderson the Rain King by Saul Bellow",
  "Humboldt's Gift by Saul Bellow",
  "Sophie's Choice by William Styron",
  "Darkness Visible by William Styron",
  "Less by Andrew Sean Greer",
  "Sweetbitter by Stephanie Danler",

  // ── Literary Fiction – British / Irish ─────────────────────────────────────
  "Lord of the Flies by William Golding",
  "Middlemarch by George Eliot",
  "Silas Marner by George Eliot",
  "The Mill on the Floss by George Eliot",
  "Jane Eyre by Charlotte Brontë",
  "Wuthering Heights by Emily Brontë",
  "Sense and Sensibility by Jane Austen",
  "Pride and Prejudice by Jane Austen",
  "Emma by Jane Austen",
  "Persuasion by Jane Austen",
  "Mansfield Park by Jane Austen",
  "Northanger Abbey by Jane Austen",
  "Great Expectations by Charles Dickens",
  "A Tale of Two Cities by Charles Dickens",
  "Bleak House by Charles Dickens",
  "David Copperfield by Charles Dickens",
  "Oliver Twist by Charles Dickens",
  "Our Mutual Friend by Charles Dickens",
  "Mrs Dalloway by Virginia Woolf",
  "To the Lighthouse by Virginia Woolf",
  "The Waves by Virginia Woolf",
  "Orlando by Virginia Woolf",
  "A Room with a View by E.M. Forster",
  "Howards End by E.M. Forster",
  "A Passage to India by E.M. Forster",
  "The Remains of the Day by Kazuo Ishiguro",
  "Never Let Me Go by Kazuo Ishiguro",
  "Klara and the Sun by Kazuo Ishiguro",
  "The Buried Giant by Kazuo Ishiguro",
  "When We Were Orphans by Kazuo Ishiguro",
  "Atonement by Ian McEwan",
  "On Chesil Beach by Ian McEwan",
  "Saturday by Ian McEwan",
  "The Child in Time by Ian McEwan",
  "Enduring Love by Ian McEwan",
  "Lessons by Ian McEwan",
  "Birdsong by Sebastian Faulks",
  "The Sense of an Ending by Julian Barnes",
  "Arthur and George by Julian Barnes",
  "Flaubert's Parrot by Julian Barnes",
  "White Teeth by Zadie Smith",
  "NW by Zadie Smith",
  "On Beauty by Zadie Smith",
  "Swing Time by Zadie Smith",
  "The Line of Beauty by Alan Hollinghurst",
  "Ulysses by James Joyce",
  "A Portrait of the Artist as a Young Man by James Joyce",
  "Dubliners by James Joyce",
  "Waiting for Godot by Samuel Beckett",
  "Molloy by Samuel Beckett",
  "Malone Dies by Samuel Beckett",
  "Trainspotting by Irvine Welsh",
  "The Wasp Factory by Iain Banks",

  // ── Literary Fiction – European ────────────────────────────────────────────
  "Les Misérables by Victor Hugo",
  "The Count of Monte Cristo by Alexandre Dumas",
  "The Three Musketeers by Alexandre Dumas",
  "Madame Bovary by Gustave Flaubert",
  "A Sentimental Education by Gustave Flaubert",
  "The Red and the Black by Stendhal",
  "Germinal by Émile Zola",
  "Nana by Émile Zola",
  "Crime and Punishment by Fyodor Dostoevsky",
  "The Brothers Karamazov by Fyodor Dostoevsky",
  "The Idiot by Fyodor Dostoevsky",
  "Notes from Underground by Fyodor Dostoevsky",
  "War and Peace by Leo Tolstoy",
  "Anna Karenina by Leo Tolstoy",
  "The Death of Ivan Ilyich by Leo Tolstoy",
  "Resurrection by Leo Tolstoy",
  "The Cherry Orchard by Anton Chekhov",
  "The Seagull by Anton Chekhov",
  "Three Sisters by Anton Chekhov",
  "Uncle Vanya by Anton Chekhov",
  "The Master and Margarita by Mikhail Bulgakov",
  "The Heart of a Dog by Mikhail Bulgakov",
  "Doctor Zhivago by Boris Pasternak",
  "The Gulag Archipelago by Aleksandr Solzhenitsyn",
  "One Day in the Life of Ivan Denisovich by Aleksandr Solzhenitsyn",
  "Lolita by Vladimir Nabokov",
  "Pale Fire by Vladimir Nabokov",
  "Speak, Memory by Vladimir Nabokov",
  "Pnin by Vladimir Nabokov",
  "Don Quixote by Miguel de Cervantes",
  "Ficciones by Jorge Luis Borges",
  "Labyrinths by Jorge Luis Borges",
  "In Search of Lost Time by Marcel Proust",
  "Swann's Way by Marcel Proust",
  "One Hundred Years of Solitude by Gabriel García Márquez",
  "Love in the Time of Cholera by Gabriel García Márquez",
  "Chronicle of a Death Foretold by Gabriel García Márquez",
  "The House of the Spirits by Isabel Allende",
  "Eva Luna by Isabel Allende",
  "Like Water for Chocolate by Laura Esquivel",
  "Pedro Páramo by Juan Rulfo",
  "The Savage Detectives by Roberto Bolaño",
  "2666 by Roberto Bolaño",
  "The Tin Drum by Günter Grass",
  "The Trial by Franz Kafka",
  "The Metamorphosis by Franz Kafka",
  "The Castle by Franz Kafka",
  "Amerika by Franz Kafka",
  "The Unbearable Lightness of Being by Milan Kundera",
  "The Book of Laughter and Forgetting by Milan Kundera",
  "The Joke by Milan Kundera",
  "Immortality by Milan Kundera",
  "If on a winter's night a traveler by Italo Calvino",
  "Invisible Cities by Italo Calvino",
  "The Baron in the Trees by Italo Calvino",
  "Cosmicomics by Italo Calvino",
  "The Name of the Rose by Umberto Eco",
  "Foucault's Pendulum by Umberto Eco",
  "My Brilliant Friend by Elena Ferrante",
  "The Story of a New Name by Elena Ferrante",
  "Those Who Leave and Those Who Stay by Elena Ferrante",
  "The Story of the Lost Child by Elena Ferrante",
  "The Days of Abandonment by Elena Ferrante",
  "The Shadow of the Wind by Carlos Ruiz Zafón",
  "The Angel's Game by Carlos Ruiz Zafón",
  "The Prisoner of Heaven by Carlos Ruiz Zafón",
  "The Labyrinth of the Spirits by Carlos Ruiz Zafón",

  // ── Literary Fiction – International / World ────────────────────────────────
  "Things Fall Apart by Chinua Achebe",
  "Arrow of God by Chinua Achebe",
  "A Man of the People by Chinua Achebe",
  "Disgrace by J.M. Coetzee",
  "Waiting for the Barbarians by J.M. Coetzee",
  "In the Heart of the Country by J.M. Coetzee",
  "Life and Times of Michael K by J.M. Coetzee",
  "Elizabeth Costello by J.M. Coetzee",
  "Summertime by J.M. Coetzee",
  "Midnight's Children by Salman Rushdie",
  "The Satanic Verses by Salman Rushdie",
  "Shame by Salman Rushdie",
  "The Moor's Last Sigh by Salman Rushdie",
  "Quichotte by Salman Rushdie",
  "Victory City by Salman Rushdie",
  "The God of Small Things by Arundhati Roy",
  "The Ministry of Utmost Happiness by Arundhati Roy",
  "A Fine Balance by Rohinton Mistry",
  "Such a Long Journey by Rohinton Mistry",
  "The White Tiger by Aravind Adiga",
  "The Palace of Illusions by Chitra Banerjee Divakaruni",
  "The Namesake by Jhumpa Lahiri",
  "Interpreter of Maladies by Jhumpa Lahiri",
  "The Lowland by Jhumpa Lahiri",
  "Snow by Orhan Pamuk",
  "My Name Is Red by Orhan Pamuk",
  "The Museum of Innocence by Orhan Pamuk",
  "Istanbul by Orhan Pamuk",
  "A Strangeness in My Mind by Orhan Pamuk",
  "Norwegian Wood by Haruki Murakami",
  "Kafka on the Shore by Haruki Murakami",
  "The Wind-Up Bird Chronicle by Haruki Murakami",
  "1Q84 by Haruki Murakami",
  "A Wild Sheep Chase by Haruki Murakami",
  "South of the Border, West of the Sun by Haruki Murakami",
  "Sputnik Sweetheart by Haruki Murakami",
  "Colorless Tsukuru Tazaki and His Years of Pilgrimage by Haruki Murakami",
  "Killing Commendatore by Haruki Murakami",
  "The City and Its Uncertain Walls by Haruki Murakami",
  "Convenience Store Woman by Sayaka Murata",
  "Earthlings by Sayaka Murata",
  "Kokoro by Natsume Soseki",
  "The Makioka Sisters by Junichiro Tanizaki",
  "The Woman in the Dunes by Kobo Abe",
];
