// Seed-cache book list, part 2/4 (split for deploy-transport size limits — see novelviz-feedback-deploy-edge-function-size-limit memory).
export const BOOKS_2: string[] = [
  "Memory Police by Yoko Ogawa",
  "The Vegetarian by Han Kang",
  "Human Acts by Han Kang",
  "The White Book by Han Kang",
  "Greek Lessons by Han Kang",
  "We Do Not Part by Han Kang",
  "Please Look After Mom by Kyung-sook Shin",
  "Half a Yellow Sun by Chimamanda Ngozi Adichie",
  "Purple Hibiscus by Chimamanda Ngozi Adichie",
  "The Kite Runner by Khaled Hosseini",
  "A Thousand Splendid Suns by Khaled Hosseini",
  "And the Mountains Echoed by Khaled Hosseini",

  // ── Modern / Contemporary ──────────────────────────────────────────────────
  "Anxious People by Fredrik Backman",
  "A Man Called Ove by Fredrik Backman",
  "Beartown by Fredrik Backman",
  "Us Against You by Fredrik Backman",
  "Eleanor Oliphant Is Completely Fine by Gail Honeyman",
  "The Midnight Library by Matt Haig",
  "How to Stop Time by Matt Haig",
  "The Humans by Matt Haig",
  "Remarkably Bright Creatures by Shelby Van Pelt",
  "Tomorrow, and Tomorrow, and Tomorrow by Gabrielle Zevin",
  "The Storied Life of A.J. Fikry by Gabrielle Zevin",
  "Lessons in Chemistry by Bonnie Garmus",
  "The Covenant of Water by Abraham Verghese",
  "Cutting for Stone by Abraham Verghese",
  "Demon Copperhead by Barbara Kingsolver",
  "The Poisonwood Bible by Barbara Kingsolver",
  "Prodigal Summer by Barbara Kingsolver",
  "The Book Thief by Markus Zusak",
  "The Guernsey Literary and Potato Peel Pie Society by Mary Ann Shaffer",
  "Where the Crawdads Sing by Delia Owens",
  "All the Light We Cannot See by Anthony Doerr",
  "Cloud Cuckoo Land by Anthony Doerr",
  "James by Percival Everett",
  "Erasure by Percival Everett",
  "The Trees by Percival Everett",
  "Piranesi by Susanna Clarke",
  "Jonathan Strange and Mr Norrell by Susanna Clarke",
  "The English Patient by Michael Ondaatje",
  "In the Skin of a Lion by Michael Ondaatje",
  "Oscar and Lucinda by Peter Carey",
  "True History of the Kelly Gang by Peter Carey",
  "The Blind Assassin by Margaret Atwood",
  "Cat's Eye by Margaret Atwood",
  "Life Before Man by Margaret Atwood",
  "The Handmaid's Tale by Margaret Atwood",
  "Alias Grace by Margaret Atwood",
  "Oryx and Crake by Margaret Atwood",
  "The Year of the Flood by Margaret Atwood",
  "MaddAddam by Margaret Atwood",
  "The Testaments by Margaret Atwood",
  "The Luminaries by Eleanor Catton",
  "A Brief History of Seven Killings by Marlon James",
  "The Sellout by Paul Beatty",
  "The Overstory by Richard Powers",
  "A Visit from the Goon Squad by Jennifer Egan",
  "Trust by Hernan Diaz",
  "Orbital by Samantha Harvey",
  "Prophet Song by Paul Lynch",
  "Kairos by Jenny Erpenbeck",
  "Our Wives Under the Sea by Julia Armfield",
  "Yellowface by R.F. Kuang",
  "Hello Beautiful by Ann Napolitano",
  "Wellness by Nathan Hill",
  "The Women by Kristin Hannah",
  "The Nightingale by Kristin Hannah",
  "Firefly Lane by Kristin Hannah",
  "Winter Garden by Kristin Hannah",

  // ── Mystery / Thriller ─────────────────────────────────────────────────────
  "Gone Girl by Gillian Flynn",
  "Sharp Objects by Gillian Flynn",
  "Dark Places by Gillian Flynn",
  "The Girl with the Dragon Tattoo by Stieg Larsson",
  "The Girl Who Played with Fire by Stieg Larsson",
  "The Girl Who Kicked the Hornets' Nest by Stieg Larsson",
  "And Then There Were None by Agatha Christie",
  "Murder on the Orient Express by Agatha Christie",
  "Death on the Nile by Agatha Christie",
  "The Murder of Roger Ackroyd by Agatha Christie",
  "Rebecca by Daphne du Maurier",
  "Jamaica Inn by Daphne du Maurier",
  "My Cousin Rachel by Daphne du Maurier",
  "The Secret History by Donna Tartt",
  "The Goldfinch by Donna Tartt",
  "The Da Vinci Code by Dan Brown",
  "Inferno by Dan Brown",
  "Angels and Demons by Dan Brown",
  "The Lost Symbol by Dan Brown",
  "In Cold Blood by Truman Capote",
  "The Big Sleep by Raymond Chandler",
  "Farewell, My Lovely by Raymond Chandler",
  "The Long Goodbye by Raymond Chandler",
  "The Maltese Falcon by Dashiell Hammett",
  "The Spy Who Came in from the Cold by John le Carré",
  "Tinker, Tailor, Soldier, Spy by John le Carré",
  "Smiley's People by John le Carré",
  "A Perfect Spy by John le Carré",
  "The Night Manager by John le Carré",
  "Our Man in Havana by Graham Greene",
  "The Quiet American by Graham Greene",
  "The Third Man by Graham Greene",
  "The Power and the Glory by Graham Greene",
  "The Girl on the Train by Paula Hawkins",
  "Into the Water by Paula Hawkins",
  "The Silent Patient by Alex Michaelides",
  "The Maidens by Alex Michaelides",
  "Verity by Colleen Hoover",
  "November 9 by Colleen Hoover",
  "It Ends with Us by Colleen Hoover",
  "Confess by Colleen Hoover",
  "Ugly Love by Colleen Hoover",
  "Reminders of Him by Colleen Hoover",
  "All Your Perfects by Colleen Hoover",
  "In the Woods by Tana French",
  "The Likeness by Tana French",
  "Faithful Place by Tana French",
  "The Searcher by Tana French",
  "Big Little Lies by Liane Moriarty",
  "Nine Perfect Strangers by Liane Moriarty",
  "The Husband's Secret by Liane Moriarty",
  "What Alice Forgot by Liane Moriarty",
  "Apples Never Fall by Liane Moriarty",
  "Behind Closed Doors by B.A. Paris",
  "The Woman in the Window by A.J. Finn",
  "Dark Matter by Blake Crouch",
  "Recursion by Blake Crouch",
  "Upgrade by Blake Crouch",

  // ── Science Fiction ─────────────────────────────────────────────────────────
  "Dune by Frank Herbert",
  "Dune Messiah by Frank Herbert",
  "Children of Dune by Frank Herbert",
  "God Emperor of Dune by Frank Herbert",
  "Foundation by Isaac Asimov",
  "Foundation and Empire by Isaac Asimov",
  "Second Foundation by Isaac Asimov",
  "I, Robot by Isaac Asimov",
  "The Caves of Steel by Isaac Asimov",
  "The Hitchhiker's Guide to the Galaxy by Douglas Adams",
  "The Restaurant at the End of the Universe by Douglas Adams",
  "Life, the Universe and Everything by Douglas Adams",
  "Neuromancer by William Gibson",
  "Count Zero by William Gibson",
  "Pattern Recognition by William Gibson",
  "Snow Crash by Neal Stephenson",
  "Cryptonomicon by Neal Stephenson",
  "Anathem by Neal Stephenson",
  "Seveneves by Neal Stephenson",
  "The Diamond Age by Neal Stephenson",
  "Ready Player One by Ernest Cline",
  "Ready Player Two by Ernest Cline",
  "Ender's Game by Orson Scott Card",
  "Speaker for the Dead by Orson Scott Card",
  "Xenocide by Orson Scott Card",
  "The Left Hand of Darkness by Ursula K. Le Guin",
  "The Dispossessed by Ursula K. Le Guin",
  "A Wizard of Earthsea by Ursula K. Le Guin",
  "The Tombs of Atuan by Ursula K. Le Guin",
  "The Farthest Shore by Ursula K. Le Guin",
  "Station Eleven by Emily St. John Mandel",
  "The Sea of Tranquility by Emily St. John Mandel",
  "The Glass Hotel by Emily St. John Mandel",
  "Project Hail Mary by Andy Weir",
  "The Martian by Andy Weir",
  "Artemis by Andy Weir",
  "The Three-Body Problem by Liu Cixin",
  "The Dark Forest by Liu Cixin",
  "Death's End by Liu Cixin",
  "The Wandering Earth by Liu Cixin",
  "All Systems Red by Martha Wells",
  "Artificial Condition by Martha Wells",
  "Rogue Protocol by Martha Wells",
  "Network Effect by Martha Wells",
  "Fahrenheit 451 by Ray Bradbury",
  "The Martian Chronicles by Ray Bradbury",
  "Something Wicked This Way Comes by Ray Bradbury",
  "The Illustrated Man by Ray Bradbury",
  "Do Androids Dream of Electric Sheep? by Philip K. Dick",
  "The Man in the High Castle by Philip K. Dick",
  "Ubik by Philip K. Dick",
  "A Scanner Darkly by Philip K. Dick",
  "VALIS by Philip K. Dick",
  "The Forever War by Joe Haldeman",
  "Flowers for Algernon by Daniel Keyes",
  "Ringworld by Larry Niven",
  "Rendezvous with Rama by Arthur C. Clarke",
  "Childhood's End by Arthur C. Clarke",
  "2001: A Space Odyssey by Arthur C. Clarke",
  "Stranger in a Strange Land by Robert A. Heinlein",
  "The Moon is a Harsh Mistress by Robert A. Heinlein",
  "Starship Troopers by Robert A. Heinlein",
  "Solaris by Stanislaw Lem",
  "The Cyberiad by Stanislaw Lem",
  "Old Man's War by John Scalzi",
  "The Power by Naomi Alderman",
  "The Fifth Season by N.K. Jemisin",
  "The Obelisk Gate by N.K. Jemisin",
  "The Stone Sky by N.K. Jemisin",
  "A Memory Called Empire by Arkady Martine",
  "A Desolation Called Peace by Arkady Martine",
  "This Is How You Lose the Time War by Amal El-Mohtar and Max Gladstone",
  "Exhalation by Ted Chiang",
  "Stories of Your Life and Others by Ted Chiang",

  // ── Fantasy ─────────────────────────────────────────────────────────────────
  "The Lord of the Rings by J.R.R. Tolkien",
  "The Hobbit by J.R.R. Tolkien",
  "The Silmarillion by J.R.R. Tolkien",
  "Children of Húrin by J.R.R. Tolkien",
  "A Game of Thrones by George R.R. Martin",
  "A Clash of Kings by George R.R. Martin",
  "A Storm of Swords by George R.R. Martin",
  "A Feast for Crows by George R.R. Martin",
  "A Dance with Dragons by George R.R. Martin",
  "Fire and Blood by George R.R. Martin",
  "The Name of the Wind by Patrick Rothfuss",
  "The Wise Man's Fear by Patrick Rothfuss",
  "The Way of Kings by Brandon Sanderson",
  "Words of Radiance by Brandon Sanderson",
  "Oathbringer by Brandon Sanderson",
  "Rhythm of War by Brandon Sanderson",
  "Wind and Truth by Brandon Sanderson",
  "The Final Empire by Brandon Sanderson",
  "The Well of Ascension by Brandon Sanderson",
  "The Hero of Ages by Brandon Sanderson",
  "Warbreaker by Brandon Sanderson",
  "Elantris by Brandon Sanderson",
  "Fourth Wing by Rebecca Yarros",
  "Iron Flame by Rebecca Yarros",
  "Onyx Storm by Rebecca Yarros",
  "The Poppy War by R.F. Kuang",
  "The Dragon Republic by R.F. Kuang",
  "The Burning God by R.F. Kuang",
  "Babel by R.F. Kuang",
  "A Court of Thorns and Roses by Sarah J. Maas",
  "A Court of Mist and Fury by Sarah J. Maas",
  "A Court of Wings and Ruin by Sarah J. Maas",
  "A Court of Silver Flames by Sarah J. Maas",
  "Throne of Glass by Sarah J. Maas",
  "Crown of Midnight by Sarah J. Maas",
  "Heir of Fire by Sarah J. Maas",
  "Queen of Shadows by Sarah J. Maas",
  "House of Earth and Blood by Sarah J. Maas",
  "House of Sky and Breath by Sarah J. Maas",
  "House of Flame and Shadow by Sarah J. Maas",
  "The Cruel Prince by Holly Black",
  "The Wicked King by Holly Black",
  "The Queen of Nothing by Holly Black",
  "An Ember in the Ashes by Sabaa Tahir",
  "A Torch Against the Night by Sabaa Tahir",
  "A Reaper at the Gates by Sabaa Tahir",
  "A Sky Beyond the Storm by Sabaa Tahir",
  "Six of Crows by Leigh Bardugo",
  "Crooked Kingdom by Leigh Bardugo",
  "Shadow and Bone by Leigh Bardugo",
  "Siege and Storm by Leigh Bardugo",
  "Ruin and Rising by Leigh Bardugo",
  "King of Scars by Leigh Bardugo",
  "The Familiar by Leigh Bardugo",
  "Harry Potter and the Philosopher's Stone by J.K. Rowling",
  "Harry Potter and the Chamber of Secrets by J.K. Rowling",
  "Harry Potter and the Prisoner of Azkaban by J.K. Rowling",
  "Harry Potter and the Goblet of Fire by J.K. Rowling",
  "Harry Potter and the Order of the Phoenix by J.K. Rowling",
  "Harry Potter and the Half-Blood Prince by J.K. Rowling",
  "Harry Potter and the Deathly Hallows by J.K. Rowling",
  "The Lies of Locke Lamora by Scott Lynch",
  "Red Seas Under Red Skies by Scott Lynch",
  "The Blade Itself by Joe Abercrombie",
  "Before They Are Hanged by Joe Abercrombie",
  "Last Argument of Kings by Joe Abercrombie",
  "Best Served Cold by Joe Abercrombie",
  "The Heroes by Joe Abercrombie",
  "A Little Hatred by Joe Abercrombie",
  "The Trouble with Peace by Joe Abercrombie",
  "The Wisdom of Crowds by Joe Abercrombie",
  "The Eye of the World by Robert Jordan",
  "The Great Hunt by Robert Jordan",
  "The Dragon Reborn by Robert Jordan",
  "Good Omens by Terry Pratchett and Neil Gaiman",
  "American Gods by Neil Gaiman",
  "Neverwhere by Neil Gaiman",
  "Stardust by Neil Gaiman",
  "Coraline by Neil Gaiman",
  "The Ocean at the End of the Lane by Neil Gaiman",
  "Norse Mythology by Neil Gaiman",
  "The Night Circus by Erin Morgenstern",
  "The Starless Sea by Erin Morgenstern",
  "The Once and Future King by T.H. White",
  "The Princess Bride by William Goldman",
  "The Chronicles of Narnia by C.S. Lewis",
  "The Lion, the Witch and the Wardrobe by C.S. Lewis",
  "The Magician's Nephew by C.S. Lewis",

  // ── Young Adult ────────────────────────────────────────────────────────────
  "The Hunger Games by Suzanne Collins",
  "Catching Fire by Suzanne Collins",
  "Mockingjay by Suzanne Collins",
  "The Ballad of Songbirds and Snakes by Suzanne Collins",
  "Divergent by Veronica Roth",
  "Insurgent by Veronica Roth",
  "Allegiant by Veronica Roth",
  "The Maze Runner by James Dashner",
  "The Scorch Trials by James Dashner",
  "The Death Cure by James Dashner",
  "Twilight by Stephenie Meyer",
  "New Moon by Stephenie Meyer",
  "Eclipse by Stephenie Meyer",
  "Breaking Dawn by Stephenie Meyer",
  "The Fault in Our Stars by John Green",
  "Paper Towns by John Green",
  "Looking for Alaska by John Green",
  "Turtles All the Way Down by John Green",
  "An Abundance of Katherines by John Green",
  "The Perks of Being a Wallflower by Stephen Chbosky",
  "Speak by Laurie Halse Anderson",
  "Thirteen Reasons Why by Jay Asher",
  "The House on Mango Street by Sandra Cisneros",
  "The Giver by Lois Lowry",
  "Gathering Blue by Lois Lowry",
  "Number the Stars by Lois Lowry",
  "Holes by Louis Sachar",
  "The Outsiders by S.E. Hinton",
  "A Monster Calls by Patrick Ness",
  "The Knife of Never Letting Go by Patrick Ness",
  "Children of Blood and Bone by Tomi Adeyemi",
  "Wonder by R.J. Palacio",
  "The House in the Cerulean Sea by TJ Klune",
  "Under the Whispering Door by TJ Klune",
  "Beach Read by Emily Henry",
  "People We Meet on Vacation by Emily Henry",
  "Book Lovers by Emily Henry",
  "Happy Place by Emily Henry",
  "The Seven Husbands of Evelyn Hugo by Taylor Jenkins Reid",
  "Daisy Jones and the Six by Taylor Jenkins Reid",
  "Icebreaker by Hannah Grace",
  "Wildfire by Hannah Grace",
  "Orphan Train by Christina Baker Kline",

  // ── Horror / Gothic ────────────────────────────────────────────────────────
  "Frankenstein by Mary Shelley",
  "Dracula by Bram Stoker",
  "The Picture of Dorian Gray by Oscar Wilde",
  "The Strange Case of Dr Jekyll and Mr Hyde by Robert Louis Stevenson",
  "The Time Machine by H.G. Wells",
  "The War of the Worlds by H.G. Wells",
  "The Invisible Man by H.G. Wells",
  "It by Stephen King",
  "The Shining by Stephen King",
  "Doctor Sleep by Stephen King",
  "The Stand by Stephen King",
  "Pet Sematary by Stephen King",
  "Misery by Stephen King",
  "Carrie by Stephen King",
  "11/22/63 by Stephen King",
  "Under the Dome by Stephen King",
  "The Dark Tower: The Gunslinger by Stephen King",
  "Different Seasons by Stephen King",
  "Night Shift by Stephen King",
  "The Haunting of Hill House by Shirley Jackson",
  "We Have Always Lived in the Castle by Shirley Jackson",
  "The Lottery by Shirley Jackson",
  "House of Leaves by Mark Z. Danielewski",
  "Mexican Gothic by Silvia Moreno-Garcia",
  "Gods of Jade and Shadow by Silvia Moreno-Garcia",
  "Bird Box by Josh Malerman",
  "Little Stranger by Sarah Waters",
  "Fingersmith by Sarah Waters",
  "Affinity by Sarah Waters",
  "The Paying Guests by Sarah Waters",

  // ── Historical Fiction ─────────────────────────────────────────────────────
  "Wolf Hall by Hilary Mantel",
  "Bring Up the Bodies by Hilary Mantel",
  "The Mirror and the Light by Hilary Mantel",
  "A Place of Greater Safety by Hilary Mantel",
  "All the Light We Cannot See by Anthony Doerr",
  "Pillars of the Earth by Ken Follett",
  "World Without End by Ken Follett",
  "A Column of Fire by Ken Follett",
  "Fall of Giants by Ken Follett",
  "Winter of the World by Ken Follett",
  "Edge of Eternity by Ken Follett",
  "Shogun by James Clavell",
  "The Last Kingdom by Bernard Cornwell",
  "Outlander by Diana Gabaldon",
  "Dragonfly in Amber by Diana Gabaldon",
  "Voyager by Diana Gabaldon",
  "Captain Corelli's Mandolin by Louis de Bernières",
  "Pachinko by Min Jin Lee",
  "Lincoln by Gore Vidal",
  "Burr by Gore Vidal",
  "The Frozen River by Ariel Lawhon",
  "Code Name Verity by Elizabeth Wein",
  "The Alice Network by Kate Quinn",
  "The Rose Code by Kate Quinn",

  // ── Spirituality / Religion ────────────────────────────────────────────────
  "The Alchemist by Paulo Coelho",
  "Eleven Minutes by Paulo Coelho",
  "The Zahir by Paulo Coelho",
  "The Autobiography of a Yogi by Paramahansa Yogananda",
  "The Book of Awakening by Mark Nepo",
  "The Essential Rumi by Coleman Barks",
  "The Divine Comedy by Dante Alighieri",
  "Paradise Lost by John Milton",
  "The Pilgrim's Progress by John Bunyan",
  "Dark Night of the Soul by John of the Cross",
  "The Interior Castle by Teresa of Ávila",
  "Revelations of Divine Love by Julian of Norwich",
  "The Imitation of Christ by Thomas à Kempis",
  "Confessions by Saint Augustine",
  "A History of God by Karen Armstrong",
  "Islam by Karen Armstrong",
  "The End of Faith by Sam Harris",
  "Letter to a Christian Nation by Sam Harris",
  "Waking Up by Sam Harris",
  "The Moral Landscape by Sam Harris",
  "The God Delusion by Richard Dawkins",
  "Breaking the Spell by Daniel C. Dennett",
  "Consciousness Explained by Daniel C. Dennett",
  "Pensées by Blaise Pascal",
  "Candide by Voltaire",
  "Power vs. Force by David R. Hawkins",
  "Becoming Supernatural by Joe Dispenza",
  "Breaking the Habit of Being Yourself by Joe Dispenza",
  "The Biology of Belief by Bruce Lipton",
  "The Four Agreements by Don Miguel Ruiz",

  // ── Graphic Novels ─────────────────────────────────────────────────────────
  "Persepolis by Marjane Satrapi",
  "Fun Home by Alison Bechdel",
  "Watchmen by Alan Moore",
  "V for Vendetta by Alan Moore",
  "From Hell by Alan Moore",
  "Dark Knight Returns by Frank Miller",
  "Sandman by Neil Gaiman",
  "American Born Chinese by Gene Luen Yang",
  "March by John Lewis and Andrew Aydin",
  "Palestine by Joe Sacco",
  "Safe Area Goražde by Joe Sacco",

  // ── Malcolm Gladwell (complete) ────────────────────────────────────────────
  "The Tipping Point by Malcolm Gladwell",
  "Blink by Malcolm Gladwell",
  "Outliers by Malcolm Gladwell",
  "What the Dog Saw by Malcolm Gladwell",
  "David and Goliath by Malcolm Gladwell",
  "Talking to Strangers by Malcolm Gladwell",
  "The Bomber Mafia by Malcolm Gladwell",
  "Revenge of the Tipping Point by Malcolm Gladwell",

  // ── Michael Lewis (complete) ───────────────────────────────────────────────
  "Liar's Poker by Michael Lewis",
  "Moneyball by Michael Lewis",
  "The Blind Side by Michael Lewis",
  "The Big Short by Michael Lewis",
  "Flash Boys by Michael Lewis",
  "The Fifth Risk by Michael Lewis",
  "The Premonition by Michael Lewis",
  "Going Infinite by Michael Lewis",
  "Boomerang by Michael Lewis",
  "The New New Thing by Michael Lewis",
  "Next by Michael Lewis",

  // ── Popular Romance / Women's Fiction ─────────────────────────────────────
  "The Hating Game by Sally Thorne",
  "Second First Impressions by Sally Thorne",
  "The Love Hypothesis by Ali Hazelwood",
  "Check and Mate by Ali Hazelwood",
  "Bride by Ali Hazelwood",
  "Stuck with You by Ali Hazelwood",
  "The Spanish Love Deception by Elena Armas",
  "The American Roommate Experiment by Elena Armas",
  "Things We Never Got Over by Lucy Score",
  "Things We Left Behind by Lucy Score",
  "Knockemout by Lucy Score",
  "The Unhoneymooners by Christina Lauren",
  "Roomies by Christina Lauren",
  "In a Holidaze by Christina Lauren",
  "Funny Story by Emily Henry",
  "Great Big Beautiful Life by Emily Henry",
  "Act Your Age Eve Brown by Talia Hibbert",
  "Get a Life Chloe Brown by Talia Hibbert",
  "Take a Hint Dani Brown by Talia Hibbert",
  "One Day in December by Josie Silver",
  "Just for the Summer by Abby Jimenez",
  "Yours Truly by Abby Jimenez",
  "Part of Your World by Abby Jimenez",
  "Life's Too Short by Abby Jimenez",
  "The Charm Offensive by Alicia Thompson",
  "Well Played by Jen DeLuca",
  "From Blood and Ash by Jennifer L. Armentrout",
  "A Shadow in the Ember by Jennifer L. Armentrout",
  "A Touch of Darkness by Scarlett St. Clair",
  "The Fine Print by Lauren Asher",

  // ── Health / Fitness / Wellness ───────────────────────────────────────────
  "Outlive by Peter Attia",
  "Can't Hurt Me by David Goggins",
  "Never Finished by David Goggins",
  "Dopamine Nation by Anna Lembke",
  "Breath by James Nestor",
  "Ikigai by Hector Garcia and Francesc Miralles",
  "The Blue Zones by Dan Buettner",
  "An Immense World by Ed Yong",
  "I Contain Multitudes by Ed Yong",
  "The Myth of Normal by Gabor Mate",
  "Scattered Minds by Gabor Mate",
  "In the Realm of Hungry Ghosts by Gabor Mate",
  "Burnout by Emily Nagoski",
  "Come as You Are by Emily Nagoski",
  "Gut by Giulia Enders",
  "The Highly Sensitive Person by Elaine N. Aron",
  "This Is Your Brain on Food by Uma Naidoo",
  "Spark by John J. Ratey",
  "The Circadian Code by Satchin Panda",
  "The Longevity Diet by Valter Longo",
  "How Not to Die by Michael Greger",
  "Immune by Philipp Dettmer",
  "Ultra-Processed People by Chris van Tulleken",
  "Sensitive by Jenn Granneman and Andre Sólo",

  // ── Parenting / Relationships ──────────────────────────────────────────────
  "The Whole-Brain Child by Daniel J. Siegel",
  "No-Drama Discipline by Daniel J. Siegel",
  "Untamed by Glennon Doyle",
  "Love Warrior by Glennon Doyle",
  "Good Inside by Becky Kennedy",
  "The Five Love Languages by Gary Chapman",
  "Mating in Captivity by Esther Perel",
  "The State of Affairs by Esther Perel",
  "All About Love by bell hooks",
  "The Will to Change by bell hooks",
  "Communion by bell hooks",
  "Why Does He Do That by Lundy Bancroft",
  "Codependent No More by Melody Beattie",
  "Boundaries by Henry Cloud and John Townsend",
  "Running on Empty by Jonice Webb",
  "The Dance of Anger by Harriet Lerner",
  "Why Won't You Apologize by Harriet Lerner",
  "Polysecure by Jessica Fern",
  "Brain-Body Parenting by Mona Delahooke",
  "Good Moms Have Scary Thoughts by Karen Kleiman",

  // ── Food Writing / Culinary Memoir ────────────────────────────────────────
  "Kitchen Confidential by Anthony Bourdain",
  "Medium Raw by Anthony Bourdain",
  "World Travel by Anthony Bourdain",
  "A Cook's Tour by Anthony Bourdain",
  "Salt Fat Acid Heat by Samin Nosrat",
  "Blood, Bones and Butter by Gabrielle Hamilton",
  "An Everlasting Meal by Tamar Adler",
  "My Life in France by Julia Child",
  "The Art of Eating by M.F.K. Fisher",
  "Consider the Oyster by M.F.K. Fisher",
  "Heat by Bill Buford",
  "Dirt by Bill Buford",
  "Fast Food Nation by Eric Schlosser",
  "The Food Lab by J. Kenji Lopez-Alt",
  "Jerusalem by Yotam Ottolenghi",
  "Plenty by Yotam Ottolenghi",
  "Plenty More by Yotam Ottolenghi",
  "Dessert Person by Claire Saffitz",
  "Cooked by Michael Pollan",
  "Mastering the Art of French Cooking by Julia Child",

  // ── Music / Film / Arts Memoir ────────────────────────────────────────────
  "Just Kids by Patti Smith",
  "M Train by Patti Smith",
  "Year of the Monkey by Patti Smith",
  "Born to Run by Bruce Springsteen",
  "Life by Keith Richards",
  "Scar Tissue by Anthony Kiedis",
  "The Dirt by Motley Crue",
  "Bossypants by Tina Fey",
  "Yes Please by Amy Poehler",
  "Is Everyone Hanging Out Without Me by Mindy Kaling",
  "Why Not Me by Mindy Kaling",
  "I Feel Bad About My Neck by Nora Ephron",
  "Heartburn by Nora Ephron",
  "Wishful Drinking by Carrie Fisher",
  "The Princess Diarist by Carrie Fisher",
  "Bad Feminist by Roxane Gay",
  "Hunger by Roxane Gay",
  "Shrill by Lindy West",
  "How to Be a Woman by Caitlin Moran",
  "We Are Never Meeting in Real Life by Samantha Irby",
  "Adventures in the Screen Trade by William Goldman",
  "Bird by Bird by Anne Lamott",
  "On Writing by Stephen King",
  "Save the Cat by Blake Snyder",
  "How Music Works by David Byrne",

  // ── Sports / Adventure Narrative ──────────────────────────────────────────
  "The Boys in the Boat by Daniel James Brown",
  "Born to Run by Christopher McDougall",
  "What I Talk About When I Talk About Running by Haruki Murakami",
  "Lone Survivor by Marcus Luttrell",
  "The Perfect Storm by Sebastian Junger",
  "Tribe by Sebastian Junger",
  "War by Sebastian Junger",
  "The Tiger by John Vaillant",
  "Left for Dead by Beck Weathers",
  "American Sniper by Chris Kyle",
  "No Easy Day by Mark Owen",
  "Between a Rock and a Hard Place by Aron Ralston",
  "Touching the Void by Joe Simpson",
  "The Feather Thief by Kirk Wallace Johnson",
  "Soccernomics by Simon Kuper and Stefan Szymanski",

  // ── More Literary Fiction ──────────────────────────────────────────────────
  "A Gentleman in Moscow by Amor Towles",
  "Rules of Civility by Amor Towles",
  "Lincoln Highway by Amor Towles",
  "Bel Canto by Ann Patchett",
  "The Dutch House by Ann Patchett",
  "Commonwealth by Ann Patchett",
  "Truth and Beauty by Ann Patchett",
  "These Precious Days by Ann Patchett",
  "Run by Ann Patchett",
  "Olive Kitteridge by Elizabeth Strout",
  "Olive Again by Elizabeth Strout",
  "My Name Is Lucy Barton by Elizabeth Strout",
  "Oh William by Elizabeth Strout",
  "Lucy by the Sea by Elizabeth Strout",
  "Tell Me Everything by Elizabeth Strout",
  "The Burgess Boys by Elizabeth Strout",
  "Peace Like a River by Leif Enger",
  "Stoner by John Williams",
  "Butcher's Crossing by John Williams",
  "Augustus by John Williams",
  "The Time Traveler's Wife by Audrey Niffenegger",
  "The Maid by Nita Prose",
  "The Lake House by Kate Morton",
  "The House at Riverton by Kate Morton",
  "The Forgotten Garden by Kate Morton",
  "The Secret Keeper by Kate Morton",
  "The Clockmaker's Daughter by Kate Morton",
  "Our Missing Hearts by Celeste Ng",
  "Everything I Never Told You by Celeste Ng",
  "Little Fires Everywhere by Celeste Ng",
  "Hamnet by Maggie O'Farrell",
  "The Marriage Portrait by Maggie O'Farrell",
  "Milkman by Anna Burns",
  "Foster by Claire Keegan",
  "Small Things Like These by Claire Keegan",
  "Young Mungo by Douglas Stuart",
  "Shuggie Bain by Douglas Stuart",
  "This Tender Land by William Kent Krueger",
  "Ordinary Grace by William Kent Krueger",
  "The River by Peter Heller",
];
