// Cache seeder — pre-populates novel_analyses for popular books so users
// get instant results on their first search.
//
// Trigger manually:
//   curl -X POST https://ecsublyvcvzdkvggxwlh.supabase.co/functions/v1/seed-cache \
//     -H "Authorization: Bearer <SUPABASE_ANON_KEY>" \
//     -H "x-seed-secret: <SEED_SECRET>" \
//     -H "Content-Type: application/json" \
//     -d '{"batch": 10, "delay_ms": 3000}'
//
// Required Supabase secret: SEED_SECRET (any random string you choose)
// Optional body params:
//   batch     — books to process per run (default 10, max 50)
//   delay_ms  — ms between Gemini calls (default 3000, min 1000)
//   dry_run   — true → only report what would be seeded, no Gemini calls

import { createClient } from "jsr:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-seed-secret",
};

// ~2000 popular books across all major genres.
// Sorted roughly by expected search frequency — top entries are seeded first.
// Run the seeder multiple times (it skips already-cached books) until pending reaches 0.
const POPULAR_BOOKS = [
  // ── Self-help / Psychology / Productivity ──────────────────────────────────
  "Sapiens by Yuval Noah Harari",
  "Homo Deus by Yuval Noah Harari",
  "21 Lessons for the 21st Century by Yuval Noah Harari",
  "Thinking, Fast and Slow by Daniel Kahneman",
  "Atomic Habits by James Clear",
  "The Power of Now by Eckhart Tolle",
  "Man's Search for Meaning by Viktor Frankl",
  "The Subtle Art of Not Giving a F*ck by Mark Manson",
  "Everything Is F*cked by Mark Manson",
  "Quiet by Susan Cain",
  "Daring Greatly by Brené Brown",
  "The Gifts of Imperfection by Brené Brown",
  "Braving the Wilderness by Brené Brown",
  "Atlas of the Heart by Brené Brown",
  "Deep Work by Cal Newport",
  "Digital Minimalism by Cal Newport",
  "So Good They Can't Ignore You by Cal Newport",
  "A World Without Email by Cal Newport",
  "Slow Productivity by Cal Newport",
  "Start With Why by Simon Sinek",
  "Leaders Eat Last by Simon Sinek",
  "The Infinite Game by Simon Sinek",
  "Find Your Why by Simon Sinek",
  "The Body Keeps the Score by Bessel van der Kolk",
  "Why We Sleep by Matthew Walker",
  "Lifespan by David Sinclair",
  "The Anxious Generation by Jonathan Haidt",
  "The Coddling of the American Mind by Jonathan Haidt",
  "The Righteous Mind by Jonathan Haidt",
  "Flow by Mihaly Csikszentmihalyi",
  "Grit by Angela Duckworth",
  "Mindset by Carol S. Dweck",
  "Drive by Daniel H. Pink",
  "A Whole New Mind by Daniel H. Pink",
  "When by Daniel H. Pink",
  "The Power of Habit by Charles Duhigg",
  "Smarter Faster Better by Charles Duhigg",
  "Stumbling on Happiness by Daniel Gilbert",
  "Predictably Irrational by Dan Ariely",
  "The Paradox of Choice by Barry Schwartz",
  "Switch by Chip Heath and Dan Heath",
  "Made to Stick by Chip Heath and Dan Heath",
  "Decisive by Chip Heath and Dan Heath",
  "The War of Art by Steven Pressfield",
  "Big Magic by Elizabeth Gilbert",
  "Eat Pray Love by Elizabeth Gilbert",
  "The Artist's Way by Julia Cameron",
  "How to Win Friends and Influence People by Dale Carnegie",
  "How to Stop Worrying and Start Living by Dale Carnegie",
  "Never Split the Difference by Chris Voss",
  "Getting to Yes by Roger Fisher",
  "Influence by Robert Cialdini",
  "Pre-Suasion by Robert Cialdini",
  "Crucial Conversations by Kerry Patterson",
  "The 7 Habits of Highly Effective People by Stephen Covey",
  "First Things First by Stephen Covey",
  "The 4-Hour Workweek by Tim Ferriss",
  "Tools of Titans by Tim Ferriss",
  "Tribe of Mentors by Tim Ferriss",
  "Essentialism by Greg McKeown",
  "Effortless by Greg McKeown",
  "The One Thing by Gary Keller",
  "Getting Things Done by David Allen",
  "Your Money or Your Life by Vicki Robin",
  "The Total Money Makeover by Dave Ramsey",
  "I Will Teach You to Be Rich by Ramit Sethi",
  "The Millionaire Next Door by Thomas J. Stanley",
  "A Random Walk Down Wall Street by Burton Malkiel",
  "The Psychology of Money by Morgan Housel",
  "Same as Ever by Morgan Housel",
  "Rich Dad Poor Dad by Robert Kiyosaki",
  "Think and Grow Rich by Napoleon Hill",
  "The Science of Getting Rich by Wallace D. Wattles",
  "The Richest Man in Babylon by George S. Clason",
  "Die With Zero by Bill Perkins",
  "Set Boundaries, Find Peace by Nedra Glennon Tawwab",
  "The Four Agreements by Don Miguel Ruiz",
  "The Fifth Agreement by Don Miguel Ruiz",
  "The Untethered Soul by Michael A. Singer",
  "The Surrender Experiment by Michael A. Singer",
  "Letting Go by David R. Hawkins",
  "Lost Connections by Johann Hari",
  "Stolen Focus by Johann Hari",
  "Chatter by Ethan Kross",
  "Think Again by Adam Grant",
  "Give and Take by Adam Grant",
  "Originals by Adam Grant",
  "Hidden Potential by Adam Grant",
  "Attached by Amir Levine and Rachel Heller",
  "The Seven Principles for Making Marriage Work by John Gottman",
  "Hold Me Tight by Sue Johnson",
  "Adult Children of Emotionally Immature Parents by Lindsay C. Gibson",
  "It Didn't Start with You by Mark Wolynn",
  "What Happened to You by Bruce D. Perry and Oprah Winfrey",
  "Complex PTSD by Pete Walker",
  "The Drama of the Gifted Child by Alice Miller",
  "Nonviolent Communication by Marshall B. Rosenberg",
  "The Road Less Travelled by M. Scott Peck",
  "When Things Fall Apart by Pema Chödrön",
  "Start Where You Are by Pema Chödrön",
  "Wherever You Go, There You Are by Jon Kabat-Zinn",
  "Full Catastrophe Living by Jon Kabat-Zinn",
  "The Miracle of Mindfulness by Thich Nhat Hanh",
  "No Mud, No Lotus by Thich Nhat Hanh",
  "Siddhartha by Hermann Hesse",
  "Steppenwolf by Hermann Hesse",
  "Demian by Hermann Hesse",
  "Be Here Now by Ram Dass",
  "A New Earth by Eckhart Tolle",

  // ── Business / Leadership / Entrepreneurship ───────────────────────────────
  "Zero to One by Peter Thiel",
  "The Hard Thing About Hard Things by Ben Horowitz",
  "Good to Great by Jim Collins",
  "Built to Last by Jim Collins",
  "Great by Choice by Jim Collins",
  "The Lean Startup by Eric Ries",
  "Rework by Jason Fried and David Heinemeier Hansson",
  "Remote by Jason Fried and David Heinemeier Hansson",
  "It Doesn't Have to Be Crazy at Work by Jason Fried and David Heinemeier Hansson",
  "The E-Myth Revisited by Michael E. Gerber",
  "Thinking in Bets by Annie Duke",
  "Principles by Ray Dalio",
  "Principles for Dealing with the Changing World Order by Ray Dalio",
  "The Innovator's Dilemma by Clayton M. Christensen",
  "The Innovator's Solution by Clayton M. Christensen",
  "Competing Against Luck by Clayton M. Christensen",
  "Crossing the Chasm by Geoffrey A. Moore",
  "Blue Ocean Strategy by W. Chan Kim and Renée Mauborgne",
  "Measure What Matters by John Doerr",
  "High Output Management by Andrew S. Grove",
  "Only the Paranoid Survive by Andrew S. Grove",
  "The Effective Executive by Peter F. Drucker",
  "Shoe Dog by Phil Knight",
  "Losing My Virginity by Richard Branson",
  "Pour Your Heart Into It by Howard Schultz",
  "Bad Blood by John Carreyrou",
  "Super Pumped by Mike Isaac",
  "No Filter by Sarah Frier",
  "The Everything Store by Brad Stone",
  "Invent and Wander by Jeff Bezos",
  "Creativity, Inc. by Ed Catmull",
  "Hit Refresh by Satya Nadella",
  "No Rules Rules by Reed Hastings and Erin Meyer",
  "The Culture Code by Daniel Coyle",
  "Trillion Dollar Coach by Eric Schmidt",
  "The Age of Surveillance Capitalism by Shoshana Zuboff",
  "The Cold Start Problem by Andrew Chen",
  "Blitzscaling by Reid Hoffman",
  "The Lean Product Playbook by Dan Olsen",
  "Continuous Discovery Habits by Teresa Torres",
  "Inspired by Marty Cagan",
  "Empowered by Marty Cagan",
  "Transformed by Marty Cagan",
  "Obviously Awesome by April Dunford",
  "The Mom Test by Rob Fitzpatrick",
  "Traction by Gabriel Weinberg and Justin Mares",
  "$100M Offers by Alex Hormozi",
  "$100M Leads by Alex Hormozi",
  "Building a StoryBrand by Donald Miller",
  "Contagious by Jonah Berger",
  "This Is Marketing by Seth Godin",
  "Linchpin by Seth Godin",
  "Purple Cow by Seth Godin",
  "Tribes by Seth Godin",
  "The Dip by Seth Godin",

  // ── History / Politics / Society ───────────────────────────────────────────
  "Guns, Germs, and Steel by Jared Diamond",
  "Collapse by Jared Diamond",
  "The Rise and Fall of the Third Reich by William L. Shirer",
  "Team of Rivals by Doris Kearns Goodwin",
  "The Warmth of Other Suns by Isabel Wilkerson",
  "Caste by Isabel Wilkerson",
  "Between the World and Me by Ta-Nehisi Coates",
  "Just Mercy by Bryan Stevenson",
  "The New Jim Crow by Michelle Alexander",
  "How to Be an Antiracist by Ibram X. Kendi",
  "Stamped from the Beginning by Ibram X. Kendi",
  "A People's History of the United States by Howard Zinn",
  "Evicted by Matthew Desmond",
  "Poverty, by America by Matthew Desmond",
  "Nickel and Dimed by Barbara Ehrenreich",
  "Capital in the Twenty-First Century by Thomas Piketty",
  "The Road to Serfdom by Friedrich Hayek",
  "The Origins of Totalitarianism by Hannah Arendt",
  "Eichmann in Jerusalem by Hannah Arendt",
  "On Tyranny by Timothy Snyder",
  "The Road to Unfreedom by Timothy Snyder",
  "Bloodlands by Timothy Snyder",
  "Ordinary Men by Christopher R. Browning",
  "Night by Elie Wiesel",
  "Maus by Art Spiegelman",
  "The Diary of a Young Girl by Anne Frank",
  "Postwar by Tony Judt",
  "The Lessons of History by Will Durant and Ariel Durant",
  "SPQR by Mary Beard",
  "Rubicon by Tom Holland",
  "Dominion by Tom Holland",
  "The Silk Roads by Peter Frankopan",
  "The Anarchy by William Dalrymple",
  "The Guns of August by Barbara Tuchman",
  "A Distant Mirror by Barbara Tuchman",
  "Churchill by Andrew Roberts",
  "Napoleon by Andrew Roberts",
  "The Second World War by Antony Beevor",
  "Stalingrad by Antony Beevor",
  "D-Day by Antony Beevor",
  "The Gulag Archipelago by Aleksandr Solzhenitsyn",
  "Mao's Great Famine by Frank Dikötter",
  "The Art of War by Sun Tzu",
  "The Prince by Niccolò Machiavelli",

  // ── Science / Technology / Ideas ───────────────────────────────────────────
  "A Brief History of Time by Stephen Hawking",
  "The Grand Design by Stephen Hawking",
  "The Selfish Gene by Richard Dawkins",
  "The God Delusion by Richard Dawkins",
  "The Blind Watchmaker by Richard Dawkins",
  "On the Origin of Species by Charles Darwin",
  "The Double Helix by James D. Watson",
  "The Gene by Siddhartha Mukherjee",
  "The Emperor of All Maladies by Siddhartha Mukherjee",
  "Being Mortal by Atul Gawande",
  "The Checklist Manifesto by Atul Gawande",
  "The Brain That Changes Itself by Norman Doidge",
  "The Man Who Mistook His Wife for a Hat by Oliver Sacks",
  "Surely You're Joking, Mr. Feynman by Richard P. Feynman",
  "The Elegant Universe by Brian Greene",
  "The Fabric of the Cosmos by Brian Greene",
  "Cosmos by Carl Sagan",
  "The Demon-Haunted World by Carl Sagan",
  "Pale Blue Dot by Carl Sagan",
  "Astrophysics for People in a Hurry by Neil deGrasse Tyson",
  "The Information by James Gleick",
  "Chaos by James Gleick",
  "The Structure of Scientific Revolutions by Thomas S. Kuhn",
  "Gödel, Escher, Bach by Douglas R. Hofstadter",
  "The Language Instinct by Steven Pinker",
  "The Blank Slate by Steven Pinker",
  "Enlightenment Now by Steven Pinker",
  "The Better Angels of Our Nature by Steven Pinker",
  "Noise by Daniel Kahneman",
  "The Innovators by Walter Isaacson",
  "Steve Jobs by Walter Isaacson",
  "Elon Musk by Walter Isaacson",
  "Leonardo da Vinci by Walter Isaacson",
  "Einstein by Walter Isaacson",
  "The Shallows by Nicholas Carr",
  "You Are Not a Gadget by Jaron Lanier",
  "The Second Machine Age by Erik Brynjolfsson and Andrew McAfee",
  "Life 3.0 by Max Tegmark",
  "Superintelligence by Nick Bostrom",
  "Human Compatible by Stuart Russell",
  "Weapons of Math Destruction by Cathy O'Neil",
  "The Alignment Problem by Brian Christian",
  "The Coming Wave by Mustafa Suleyman",
  "Co-Intelligence by Ethan Mollick",
  "A Crack in Creation by Jennifer Doudna",
  "Behave by Robert M. Sapolsky",
  "Why Zebras Don't Get Ulcers by Robert M. Sapolsky",
  "Determined by Robert M. Sapolsky",
  "The Sixth Extinction by Elizabeth Kolbert",
  "The Uninhabitable Earth by David Wallace-Wells",
  "This Changes Everything by Naomi Klein",
  "Silent Spring by Rachel Carson",
  "Braiding Sweetgrass by Robin Wall Kimmerer",
  "The Hidden Life of Trees by Peter Wohlleben",
  "Finding the Mother Tree by Suzanne Simard",
  "The Botany of Desire by Michael Pollan",
  "In Defence of Food by Michael Pollan",
  "The Omnivore's Dilemma by Michael Pollan",
  "How to Change Your Mind by Michael Pollan",
  "Freakonomics by Steven D. Levitt and Stephen J. Dubner",
  "SuperFreakonomics by Steven D. Levitt and Stephen J. Dubner",
  "Misbehaving by Richard Thaler",
  "Nudge by Richard Thaler and Cass Sunstein",
  "The Black Swan by Nassim Nicholas Taleb",
  "Fooled by Randomness by Nassim Nicholas Taleb",
  "Antifragile by Nassim Nicholas Taleb",
  "Skin in the Game by Nassim Nicholas Taleb",

  // ── Biography / Memoir ─────────────────────────────────────────────────────
  "Educated by Tara Westover",
  "Becoming by Michelle Obama",
  "The Light We Carry by Michelle Obama",
  "A Promised Land by Barack Obama",
  "Dreams from My Father by Barack Obama",
  "Long Walk to Freedom by Nelson Mandela",
  "I Know Why the Caged Bird Sings by Maya Angelou",
  "When Breath Becomes Air by Paul Kalanithi",
  "The Year of Magical Thinking by Joan Didion",
  "Lab Girl by Hope Jahren",
  "Born a Crime by Trevor Noah",
  "The Glass Castle by Jeannette Walls",
  "Americanah by Chimamanda Ngozi Adichie",
  "We Should All Be Feminists by Chimamanda Ngozi Adichie",
  "A Long Way Gone by Ishmael Beah",
  "Persepolis by Marjane Satrapi",
  "Maus by Art Spiegelman",
  "Fun Home by Alison Bechdel",
  "The Autobiography of Malcolm X by Malcolm X",
  "Wild by Cheryl Strayed",
  "Tiny Beautiful Things by Cheryl Strayed",
  "A Walk in the Woods by Bill Bryson",
  "In a Sunburned Country by Bill Bryson",
  "Notes from a Small Island by Bill Bryson",
  "A Short History of Nearly Everything by Bill Bryson",
  "The Body by Bill Bryson",
  "Into the Wild by Jon Krakauer",
  "Into Thin Air by Jon Krakauer",
  "Under the Banner of Heaven by Jon Krakauer",
  "Endurance by Alfred Lansing",
  "Unbroken by Laura Hillenbrand",
  "Seabiscuit by Laura Hillenbrand",
  "The Immortal Life of Henrietta Lacks by Rebecca Skloot",
  "Devil in the White City by Erik Larson",
  "Dead Wake by Erik Larson",
  "In the Garden of Beasts by Erik Larson",
  "Say Nothing by Patrick Radden Keefe",
  "Empire of Pain by Patrick Radden Keefe",
  "Columbine by Dave Cullen",
  "I'll Be Gone in the Dark by Michelle McNamara",
  "Killers of the Flower Moon by David Grann",
  "The Wager by David Grann",
  "The Lost City of Z by David Grann",
  "The Radium Girls by Kate Moore",
  "I'm Glad My Mom Died by Jennette McCurdy",
  "Greenlights by Matthew McConaughey",
  "Spare by Prince Harry",
  "Finding Me by Viola Davis",
  "Open by Andre Agassi",
  "Unreasonable Hospitality by Will Guidara",

  // ── Philosophy / Classics ──────────────────────────────────────────────────
  "Meditations by Marcus Aurelius",
  "Letters from a Stoic by Seneca",
  "On the Shortness of Life by Seneca",
  "Discourses by Epictetus",
  "The Enchiridion by Epictetus",
  "Nicomachean Ethics by Aristotle",
  "The Republic by Plato",
  "Symposium by Plato",
  "Thus Spoke Zarathustra by Friedrich Nietzsche",
  "Beyond Good and Evil by Friedrich Nietzsche",
  "On the Genealogy of Morality by Friedrich Nietzsche",
  "The Gay Science by Friedrich Nietzsche",
  "Being and Nothingness by Jean-Paul Sartre",
  "Nausea by Jean-Paul Sartre",
  "The Second Sex by Simone de Beauvoir",
  "The Ethics of Ambiguity by Simone de Beauvoir",
  "The Myth of Sisyphus by Albert Camus",
  "The Rebel by Albert Camus",
  "Critique of Pure Reason by Immanuel Kant",
  "Groundwork of the Metaphysics of Morals by Immanuel Kant",
  "The Communist Manifesto by Karl Marx",
  "The Wealth of Nations by Adam Smith",
  "Leviathan by Thomas Hobbes",
  "Two Treatises of Government by John Locke",
  "A Treatise of Human Nature by David Hume",
  "The Social Contract by Jean-Jacques Rousseau",
  "On Liberty by John Stuart Mill",
  "Utilitarianism by John Stuart Mill",
  "Fear and Trembling by Søren Kierkegaard",
  "The World as Will and Representation by Arthur Schopenhauer",
  "Essays and Aphorisms by Arthur Schopenhauer",
  "A Theory of Justice by John Rawls",
  "The Obstacle Is the Way by Ryan Holiday",
  "Ego Is the Enemy by Ryan Holiday",
  "The Daily Stoic by Ryan Holiday",
  "Stillness Is the Key by Ryan Holiday",
  "Courage Is Calling by Ryan Holiday",
  "Discipline Is Destiny by Ryan Holiday",
  "The 48 Laws of Power by Robert Greene",
  "Mastery by Robert Greene",
  "The Laws of Human Nature by Robert Greene",
  "The Art of Seduction by Robert Greene",
  "The 33 Strategies of War by Robert Greene",

  // ── Literary Fiction – American ────────────────────────────────────────────
  "To Kill a Mockingbird by Harper Lee",
  "1984 by George Orwell",
  "Animal Farm by George Orwell",
  "Brave New World by Aldous Huxley",
  "The Great Gatsby by F. Scott Fitzgerald",
  "Tender Is the Night by F. Scott Fitzgerald",
  "Of Mice and Men by John Steinbeck",
  "The Grapes of Wrath by John Steinbeck",
  "East of Eden by John Steinbeck",
  "Cannery Row by John Steinbeck",
  "The Catcher in the Rye by J.D. Salinger",
  "Franny and Zooey by J.D. Salinger",
  "The Old Man and the Sea by Ernest Hemingway",
  "A Farewell to Arms by Ernest Hemingway",
  "For Whom the Bell Tolls by Ernest Hemingway",
  "The Sun Also Rises by Ernest Hemingway",
  "A Moveable Feast by Ernest Hemingway",
  "Moby Dick by Herman Melville",
  "The Scarlet Letter by Nathaniel Hawthorne",
  "Adventures of Huckleberry Finn by Mark Twain",
  "The Adventures of Tom Sawyer by Mark Twain",
  "The Road by Cormac McCarthy",
  "Blood Meridian by Cormac McCarthy",
  "No Country for Old Men by Cormac McCarthy",
  "All the Pretty Horses by Cormac McCarthy",
  "The Passenger by Cormac McCarthy",
  "Normal People by Sally Rooney",
  "Conversations with Friends by Sally Rooney",
  "Beautiful World, Where Are You by Sally Rooney",
  "Intermezzo by Sally Rooney",
  "A Little Life by Hanya Yanagihara",
  "The People in the Trees by Hanya Yanagihara",
  "To Paradise by Hanya Yanagihara",
  "The Sympathizer by Viet Thanh Nguyen",
  "The Committed by Viet Thanh Nguyen",
  "Lincoln in the Bardo by George Saunders",
  "Tenth of December by George Saunders",
  "Fleishman Is in Trouble by Taffy Brodesser-Akner",
  "Pachinko by Min Jin Lee",
  "White Noise by Don DeLillo",
  "Underworld by Don DeLillo",
  "Libra by Don DeLillo",
  "Infinite Jest by David Foster Wallace",
  "The Pale King by David Foster Wallace",
  "The Corrections by Jonathan Franzen",
  "Freedom by Jonathan Franzen",
  "Purity by Jonathan Franzen",
  "Crossroads by Jonathan Franzen",
  "Gilead by Marilynne Robinson",
  "Housekeeping by Marilynne Robinson",
  "Home by Marilynne Robinson",
  "Lila by Marilynne Robinson",
  "Beloved by Toni Morrison",
  "Song of Solomon by Toni Morrison",
  "Sula by Toni Morrison",
  "The Bluest Eye by Toni Morrison",
  "Jazz by Toni Morrison",
  "Their Eyes Were Watching God by Zora Neale Hurston",
  "Invisible Man by Ralph Ellison",
  "The Color Purple by Alice Walker",
  "Go Tell It on the Mountain by James Baldwin",
  "Giovanni's Room by James Baldwin",
  "Another Country by James Baldwin",
  "The Fire Next Time by James Baldwin",
  "If Beale Street Could Talk by James Baldwin",
  "Kindred by Octavia Butler",
  "Parable of the Sower by Octavia Butler",
  "Parable of the Talents by Octavia Butler",
  "The Crying of Lot 49 by Thomas Pynchon",
  "Gravity's Rainbow by Thomas Pynchon",
  "My Year of Rest and Relaxation by Ottessa Moshfegh",
  "Eileen by Ottessa Moshfegh",
  "Lapvona by Ottessa Moshfegh",
  "A Visit from the Goon Squad by Jennifer Egan",
  "The Virgin Suicides by Jeffrey Eugenides",
  "Middlesex by Jeffrey Eugenides",
  "The Marriage Plot by Jeffrey Eugenides",
  "American Pastoral by Philip Roth",
  "The Human Stain by Philip Roth",
  "Sabbath's Theater by Philip Roth",
  "Portnoy's Complaint by Philip Roth",
  "The Plot Against America by Philip Roth",
  "The Bell Jar by Sylvia Plath",
  "On the Road by Jack Kerouac",
  "The Dharma Bums by Jack Kerouac",
  "A Streetcar Named Desire by Tennessee Williams",
  "The Glass Menagerie by Tennessee Williams",
  "Death of a Salesman by Arthur Miller",
  "The Crucible by Arthur Miller",
  "Catch-22 by Joseph Heller",
  "Something Happened by Joseph Heller",
  "Slaughterhouse-Five by Kurt Vonnegut",
  "Cat's Cradle by Kurt Vonnegut",
  "Breakfast of Champions by Kurt Vonnegut",
  "Mother Night by Kurt Vonnegut",
  "One Flew Over the Cuckoo's Nest by Ken Kesey",
  "The Adventures of Augie March by Saul Bellow",
  "Herzog by Saul Bellow",
  "Henderson the Rain King by Saul Bellow",
  "Humboldt's Gift by Saul Bellow",
  "Sophie's Choice by William Styron",
  "Darkness Visible by William Styron",
  "Less by Andrew Sean Greer",
  "Sweetbitter by Stephanie Danler",

  // ── Literary Fiction – British / Irish ─────────────────────────────────────
  "Lord of the Flies by William Golding",
  "Middlemarch by George Eliot",
  "Silas Marner by George Eliot",
  "The Mill on the Floss by George Eliot",
  "Jane Eyre by Charlotte Brontë",
  "Wuthering Heights by Emily Brontë",
  "Sense and Sensibility by Jane Austen",
  "Pride and Prejudice by Jane Austen",
  "Emma by Jane Austen",
  "Persuasion by Jane Austen",
  "Mansfield Park by Jane Austen",
  "Northanger Abbey by Jane Austen",
  "Great Expectations by Charles Dickens",
  "A Tale of Two Cities by Charles Dickens",
  "Bleak House by Charles Dickens",
  "David Copperfield by Charles Dickens",
  "Oliver Twist by Charles Dickens",
  "Our Mutual Friend by Charles Dickens",
  "Mrs Dalloway by Virginia Woolf",
  "To the Lighthouse by Virginia Woolf",
  "The Waves by Virginia Woolf",
  "Orlando by Virginia Woolf",
  "A Room with a View by E.M. Forster",
  "Howards End by E.M. Forster",
  "A Passage to India by E.M. Forster",
  "The Remains of the Day by Kazuo Ishiguro",
  "Never Let Me Go by Kazuo Ishiguro",
  "Klara and the Sun by Kazuo Ishiguro",
  "The Buried Giant by Kazuo Ishiguro",
  "When We Were Orphans by Kazuo Ishiguro",
  "Atonement by Ian McEwan",
  "On Chesil Beach by Ian McEwan",
  "Saturday by Ian McEwan",
  "The Child in Time by Ian McEwan",
  "Enduring Love by Ian McEwan",
  "Lessons by Ian McEwan",
  "Birdsong by Sebastian Faulks",
  "The Sense of an Ending by Julian Barnes",
  "Arthur and George by Julian Barnes",
  "Flaubert's Parrot by Julian Barnes",
  "White Teeth by Zadie Smith",
  "NW by Zadie Smith",
  "On Beauty by Zadie Smith",
  "Swing Time by Zadie Smith",
  "The Line of Beauty by Alan Hollinghurst",
  "Ulysses by James Joyce",
  "A Portrait of the Artist as a Young Man by James Joyce",
  "Dubliners by James Joyce",
  "Waiting for Godot by Samuel Beckett",
  "Molloy by Samuel Beckett",
  "Malone Dies by Samuel Beckett",
  "Trainspotting by Irvine Welsh",
  "The Wasp Factory by Iain Banks",

  // ── Literary Fiction – European ────────────────────────────────────────────
  "Les Misérables by Victor Hugo",
  "The Count of Monte Cristo by Alexandre Dumas",
  "The Three Musketeers by Alexandre Dumas",
  "Madame Bovary by Gustave Flaubert",
  "A Sentimental Education by Gustave Flaubert",
  "The Red and the Black by Stendhal",
  "Germinal by Émile Zola",
  "Nana by Émile Zola",
  "Crime and Punishment by Fyodor Dostoevsky",
  "The Brothers Karamazov by Fyodor Dostoevsky",
  "The Idiot by Fyodor Dostoevsky",
  "Notes from Underground by Fyodor Dostoevsky",
  "War and Peace by Leo Tolstoy",
  "Anna Karenina by Leo Tolstoy",
  "The Death of Ivan Ilyich by Leo Tolstoy",
  "Resurrection by Leo Tolstoy",
  "The Cherry Orchard by Anton Chekhov",
  "The Seagull by Anton Chekhov",
  "Three Sisters by Anton Chekhov",
  "Uncle Vanya by Anton Chekhov",
  "The Master and Margarita by Mikhail Bulgakov",
  "The Heart of a Dog by Mikhail Bulgakov",
  "Doctor Zhivago by Boris Pasternak",
  "The Gulag Archipelago by Aleksandr Solzhenitsyn",
  "One Day in the Life of Ivan Denisovich by Aleksandr Solzhenitsyn",
  "Lolita by Vladimir Nabokov",
  "Pale Fire by Vladimir Nabokov",
  "Speak, Memory by Vladimir Nabokov",
  "Pnin by Vladimir Nabokov",
  "Don Quixote by Miguel de Cervantes",
  "Ficciones by Jorge Luis Borges",
  "Labyrinths by Jorge Luis Borges",
  "In Search of Lost Time by Marcel Proust",
  "Swann's Way by Marcel Proust",
  "One Hundred Years of Solitude by Gabriel García Márquez",
  "Love in the Time of Cholera by Gabriel García Márquez",
  "Chronicle of a Death Foretold by Gabriel García Márquez",
  "The House of the Spirits by Isabel Allende",
  "Eva Luna by Isabel Allende",
  "Like Water for Chocolate by Laura Esquivel",
  "Pedro Páramo by Juan Rulfo",
  "The Savage Detectives by Roberto Bolaño",
  "2666 by Roberto Bolaño",
  "The Tin Drum by Günter Grass",
  "The Trial by Franz Kafka",
  "The Metamorphosis by Franz Kafka",
  "The Castle by Franz Kafka",
  "Amerika by Franz Kafka",
  "The Unbearable Lightness of Being by Milan Kundera",
  "The Book of Laughter and Forgetting by Milan Kundera",
  "The Joke by Milan Kundera",
  "Immortality by Milan Kundera",
  "If on a winter's night a traveler by Italo Calvino",
  "Invisible Cities by Italo Calvino",
  "The Baron in the Trees by Italo Calvino",
  "Cosmicomics by Italo Calvino",
  "The Name of the Rose by Umberto Eco",
  "Foucault's Pendulum by Umberto Eco",
  "My Brilliant Friend by Elena Ferrante",
  "The Story of a New Name by Elena Ferrante",
  "Those Who Leave and Those Who Stay by Elena Ferrante",
  "The Story of the Lost Child by Elena Ferrante",
  "The Days of Abandonment by Elena Ferrante",
  "The Shadow of the Wind by Carlos Ruiz Zafón",
  "The Angel's Game by Carlos Ruiz Zafón",
  "The Prisoner of Heaven by Carlos Ruiz Zafón",
  "The Labyrinth of the Spirits by Carlos Ruiz Zafón",

  // ── Literary Fiction – International / World ────────────────────────────────
  "Things Fall Apart by Chinua Achebe",
  "Arrow of God by Chinua Achebe",
  "A Man of the People by Chinua Achebe",
  "Disgrace by J.M. Coetzee",
  "Waiting for the Barbarians by J.M. Coetzee",
  "In the Heart of the Country by J.M. Coetzee",
  "Life and Times of Michael K by J.M. Coetzee",
  "Elizabeth Costello by J.M. Coetzee",
  "Summertime by J.M. Coetzee",
  "Midnight's Children by Salman Rushdie",
  "The Satanic Verses by Salman Rushdie",
  "Shame by Salman Rushdie",
  "The Moor's Last Sigh by Salman Rushdie",
  "Quichotte by Salman Rushdie",
  "Victory City by Salman Rushdie",
  "The God of Small Things by Arundhati Roy",
  "The Ministry of Utmost Happiness by Arundhati Roy",
  "A Fine Balance by Rohinton Mistry",
  "Such a Long Journey by Rohinton Mistry",
  "The White Tiger by Aravind Adiga",
  "The Palace of Illusions by Chitra Banerjee Divakaruni",
  "The Namesake by Jhumpa Lahiri",
  "Interpreter of Maladies by Jhumpa Lahiri",
  "The Lowland by Jhumpa Lahiri",
  "Snow by Orhan Pamuk",
  "My Name Is Red by Orhan Pamuk",
  "The Museum of Innocence by Orhan Pamuk",
  "Istanbul by Orhan Pamuk",
  "A Strangeness in My Mind by Orhan Pamuk",
  "Norwegian Wood by Haruki Murakami",
  "Kafka on the Shore by Haruki Murakami",
  "The Wind-Up Bird Chronicle by Haruki Murakami",
  "1Q84 by Haruki Murakami",
  "A Wild Sheep Chase by Haruki Murakami",
  "South of the Border, West of the Sun by Haruki Murakami",
  "Sputnik Sweetheart by Haruki Murakami",
  "Colorless Tsukuru Tazaki and His Years of Pilgrimage by Haruki Murakami",
  "Killing Commendatore by Haruki Murakami",
  "The City and Its Uncertain Walls by Haruki Murakami",
  "Convenience Store Woman by Sayaka Murata",
  "Earthlings by Sayaka Murata",
  "Kokoro by Natsume Soseki",
  "The Makioka Sisters by Junichiro Tanizaki",
  "The Woman in the Dunes by Kobo Abe",
  "Memory Police by Yoko Ogawa",
  "The Vegetarian by Han Kang",
  "Human Acts by Han Kang",
  "The White Book by Han Kang",
  "Greek Lessons by Han Kang",
  "We Do Not Part by Han Kang",
  "Please Look After Mom by Kyung-sook Shin",
  "Half a Yellow Sun by Chimamanda Ngozi Adichie",
  "Purple Hibiscus by Chimamanda Ngozi Adichie",
  "The Kite Runner by Khaled Hosseini",
  "A Thousand Splendid Suns by Khaled Hosseini",
  "And the Mountains Echoed by Khaled Hosseini",

  // ── Modern / Contemporary ──────────────────────────────────────────────────
  "Anxious People by Fredrik Backman",
  "A Man Called Ove by Fredrik Backman",
  "Beartown by Fredrik Backman",
  "Us Against You by Fredrik Backman",
  "Eleanor Oliphant Is Completely Fine by Gail Honeyman",
  "The Midnight Library by Matt Haig",
  "How to Stop Time by Matt Haig",
  "The Humans by Matt Haig",
  "Remarkably Bright Creatures by Shelby Van Pelt",
  "Tomorrow, and Tomorrow, and Tomorrow by Gabrielle Zevin",
  "The Storied Life of A.J. Fikry by Gabrielle Zevin",
  "Lessons in Chemistry by Bonnie Garmus",
  "The Covenant of Water by Abraham Verghese",
  "Cutting for Stone by Abraham Verghese",
  "Demon Copperhead by Barbara Kingsolver",
  "The Poisonwood Bible by Barbara Kingsolver",
  "Prodigal Summer by Barbara Kingsolver",
  "The Book Thief by Markus Zusak",
  "The Guernsey Literary and Potato Peel Pie Society by Mary Ann Shaffer",
  "Where the Crawdads Sing by Delia Owens",
  "All the Light We Cannot See by Anthony Doerr",
  "Cloud Cuckoo Land by Anthony Doerr",
  "James by Percival Everett",
  "Erasure by Percival Everett",
  "The Trees by Percival Everett",
  "Piranesi by Susanna Clarke",
  "Jonathan Strange and Mr Norrell by Susanna Clarke",
  "The English Patient by Michael Ondaatje",
  "In the Skin of a Lion by Michael Ondaatje",
  "Oscar and Lucinda by Peter Carey",
  "True History of the Kelly Gang by Peter Carey",
  "The Blind Assassin by Margaret Atwood",
  "Cat's Eye by Margaret Atwood",
  "Life Before Man by Margaret Atwood",
  "The Handmaid's Tale by Margaret Atwood",
  "Alias Grace by Margaret Atwood",
  "Oryx and Crake by Margaret Atwood",
  "The Year of the Flood by Margaret Atwood",
  "MaddAddam by Margaret Atwood",
  "The Testaments by Margaret Atwood",
  "The Luminaries by Eleanor Catton",
  "A Brief History of Seven Killings by Marlon James",
  "The Sellout by Paul Beatty",
  "The Overstory by Richard Powers",
  "A Visit from the Goon Squad by Jennifer Egan",
  "Trust by Hernan Diaz",
  "Orbital by Samantha Harvey",
  "Prophet Song by Paul Lynch",
  "Kairos by Jenny Erpenbeck",
  "Our Wives Under the Sea by Julia Armfield",
  "Yellowface by R.F. Kuang",
  "Hello Beautiful by Ann Napolitano",
  "Wellness by Nathan Hill",
  "The Women by Kristin Hannah",
  "The Nightingale by Kristin Hannah",
  "Firefly Lane by Kristin Hannah",
  "Winter Garden by Kristin Hannah",

  // ── Mystery / Thriller ─────────────────────────────────────────────────────
  "Gone Girl by Gillian Flynn",
  "Sharp Objects by Gillian Flynn",
  "Dark Places by Gillian Flynn",
  "The Girl with the Dragon Tattoo by Stieg Larsson",
  "The Girl Who Played with Fire by Stieg Larsson",
  "The Girl Who Kicked the Hornets' Nest by Stieg Larsson",
  "And Then There Were None by Agatha Christie",
  "Murder on the Orient Express by Agatha Christie",
  "Death on the Nile by Agatha Christie",
  "The Murder of Roger Ackroyd by Agatha Christie",
  "Rebecca by Daphne du Maurier",
  "Jamaica Inn by Daphne du Maurier",
  "My Cousin Rachel by Daphne du Maurier",
  "The Secret History by Donna Tartt",
  "The Goldfinch by Donna Tartt",
  "The Da Vinci Code by Dan Brown",
  "Inferno by Dan Brown",
  "Angels and Demons by Dan Brown",
  "The Lost Symbol by Dan Brown",
  "In Cold Blood by Truman Capote",
  "The Big Sleep by Raymond Chandler",
  "Farewell, My Lovely by Raymond Chandler",
  "The Long Goodbye by Raymond Chandler",
  "The Maltese Falcon by Dashiell Hammett",
  "The Spy Who Came in from the Cold by John le Carré",
  "Tinker, Tailor, Soldier, Spy by John le Carré",
  "Smiley's People by John le Carré",
  "A Perfect Spy by John le Carré",
  "The Night Manager by John le Carré",
  "Our Man in Havana by Graham Greene",
  "The Quiet American by Graham Greene",
  "The Third Man by Graham Greene",
  "The Power and the Glory by Graham Greene",
  "The Girl on the Train by Paula Hawkins",
  "Into the Water by Paula Hawkins",
  "The Silent Patient by Alex Michaelides",
  "The Maidens by Alex Michaelides",
  "Verity by Colleen Hoover",
  "November 9 by Colleen Hoover",
  "It Ends with Us by Colleen Hoover",
  "Confess by Colleen Hoover",
  "Ugly Love by Colleen Hoover",
  "Reminders of Him by Colleen Hoover",
  "All Your Perfects by Colleen Hoover",
  "In the Woods by Tana French",
  "The Likeness by Tana French",
  "Faithful Place by Tana French",
  "The Searcher by Tana French",
  "Big Little Lies by Liane Moriarty",
  "Nine Perfect Strangers by Liane Moriarty",
  "The Husband's Secret by Liane Moriarty",
  "What Alice Forgot by Liane Moriarty",
  "Apples Never Fall by Liane Moriarty",
  "Behind Closed Doors by B.A. Paris",
  "The Woman in the Window by A.J. Finn",
  "Dark Matter by Blake Crouch",
  "Recursion by Blake Crouch",
  "Upgrade by Blake Crouch",

  // ── Science Fiction ─────────────────────────────────────────────────────────
  "Dune by Frank Herbert",
  "Dune Messiah by Frank Herbert",
  "Children of Dune by Frank Herbert",
  "God Emperor of Dune by Frank Herbert",
  "Foundation by Isaac Asimov",
  "Foundation and Empire by Isaac Asimov",
  "Second Foundation by Isaac Asimov",
  "I, Robot by Isaac Asimov",
  "The Caves of Steel by Isaac Asimov",
  "The Hitchhiker's Guide to the Galaxy by Douglas Adams",
  "The Restaurant at the End of the Universe by Douglas Adams",
  "Life, the Universe and Everything by Douglas Adams",
  "Neuromancer by William Gibson",
  "Count Zero by William Gibson",
  "Pattern Recognition by William Gibson",
  "Snow Crash by Neal Stephenson",
  "Cryptonomicon by Neal Stephenson",
  "Anathem by Neal Stephenson",
  "Seveneves by Neal Stephenson",
  "The Diamond Age by Neal Stephenson",
  "Ready Player One by Ernest Cline",
  "Ready Player Two by Ernest Cline",
  "Ender's Game by Orson Scott Card",
  "Speaker for the Dead by Orson Scott Card",
  "Xenocide by Orson Scott Card",
  "The Left Hand of Darkness by Ursula K. Le Guin",
  "The Dispossessed by Ursula K. Le Guin",
  "A Wizard of Earthsea by Ursula K. Le Guin",
  "The Tombs of Atuan by Ursula K. Le Guin",
  "The Farthest Shore by Ursula K. Le Guin",
  "Station Eleven by Emily St. John Mandel",
  "The Sea of Tranquility by Emily St. John Mandel",
  "The Glass Hotel by Emily St. John Mandel",
  "Project Hail Mary by Andy Weir",
  "The Martian by Andy Weir",
  "Artemis by Andy Weir",
  "The Three-Body Problem by Liu Cixin",
  "The Dark Forest by Liu Cixin",
  "Death's End by Liu Cixin",
  "The Wandering Earth by Liu Cixin",
  "All Systems Red by Martha Wells",
  "Artificial Condition by Martha Wells",
  "Rogue Protocol by Martha Wells",
  "Network Effect by Martha Wells",
  "Fahrenheit 451 by Ray Bradbury",
  "The Martian Chronicles by Ray Bradbury",
  "Something Wicked This Way Comes by Ray Bradbury",
  "The Illustrated Man by Ray Bradbury",
  "Do Androids Dream of Electric Sheep? by Philip K. Dick",
  "The Man in the High Castle by Philip K. Dick",
  "Ubik by Philip K. Dick",
  "A Scanner Darkly by Philip K. Dick",
  "VALIS by Philip K. Dick",
  "The Forever War by Joe Haldeman",
  "Flowers for Algernon by Daniel Keyes",
  "Ringworld by Larry Niven",
  "Rendezvous with Rama by Arthur C. Clarke",
  "Childhood's End by Arthur C. Clarke",
  "2001: A Space Odyssey by Arthur C. Clarke",
  "Stranger in a Strange Land by Robert A. Heinlein",
  "The Moon is a Harsh Mistress by Robert A. Heinlein",
  "Starship Troopers by Robert A. Heinlein",
  "Solaris by Stanislaw Lem",
  "The Cyberiad by Stanislaw Lem",
  "Old Man's War by John Scalzi",
  "The Power by Naomi Alderman",
  "The Fifth Season by N.K. Jemisin",
  "The Obelisk Gate by N.K. Jemisin",
  "The Stone Sky by N.K. Jemisin",
  "A Memory Called Empire by Arkady Martine",
  "A Desolation Called Peace by Arkady Martine",
  "This Is How You Lose the Time War by Amal El-Mohtar and Max Gladstone",
  "Exhalation by Ted Chiang",
  "Stories of Your Life and Others by Ted Chiang",

  // ── Fantasy ─────────────────────────────────────────────────────────────────
  "The Lord of the Rings by J.R.R. Tolkien",
  "The Hobbit by J.R.R. Tolkien",
  "The Silmarillion by J.R.R. Tolkien",
  "Children of Húrin by J.R.R. Tolkien",
  "A Game of Thrones by George R.R. Martin",
  "A Clash of Kings by George R.R. Martin",
  "A Storm of Swords by George R.R. Martin",
  "A Feast for Crows by George R.R. Martin",
  "A Dance with Dragons by George R.R. Martin",
  "Fire and Blood by George R.R. Martin",
  "The Name of the Wind by Patrick Rothfuss",
  "The Wise Man's Fear by Patrick Rothfuss",
  "The Way of Kings by Brandon Sanderson",
  "Words of Radiance by Brandon Sanderson",
  "Oathbringer by Brandon Sanderson",
  "Rhythm of War by Brandon Sanderson",
  "Wind and Truth by Brandon Sanderson",
  "The Final Empire by Brandon Sanderson",
  "The Well of Ascension by Brandon Sanderson",
  "The Hero of Ages by Brandon Sanderson",
  "Warbreaker by Brandon Sanderson",
  "Elantris by Brandon Sanderson",
  "Fourth Wing by Rebecca Yarros",
  "Iron Flame by Rebecca Yarros",
  "Onyx Storm by Rebecca Yarros",
  "The Poppy War by R.F. Kuang",
  "The Dragon Republic by R.F. Kuang",
  "The Burning God by R.F. Kuang",
  "Babel by R.F. Kuang",
  "A Court of Thorns and Roses by Sarah J. Maas",
  "A Court of Mist and Fury by Sarah J. Maas",
  "A Court of Wings and Ruin by Sarah J. Maas",
  "A Court of Silver Flames by Sarah J. Maas",
  "Throne of Glass by Sarah J. Maas",
  "Crown of Midnight by Sarah J. Maas",
  "Heir of Fire by Sarah J. Maas",
  "Queen of Shadows by Sarah J. Maas",
  "House of Earth and Blood by Sarah J. Maas",
  "House of Sky and Breath by Sarah J. Maas",
  "House of Flame and Shadow by Sarah J. Maas",
  "The Cruel Prince by Holly Black",
  "The Wicked King by Holly Black",
  "The Queen of Nothing by Holly Black",
  "An Ember in the Ashes by Sabaa Tahir",
  "A Torch Against the Night by Sabaa Tahir",
  "A Reaper at the Gates by Sabaa Tahir",
  "A Sky Beyond the Storm by Sabaa Tahir",
  "Six of Crows by Leigh Bardugo",
  "Crooked Kingdom by Leigh Bardugo",
  "Shadow and Bone by Leigh Bardugo",
  "Siege and Storm by Leigh Bardugo",
  "Ruin and Rising by Leigh Bardugo",
  "King of Scars by Leigh Bardugo",
  "The Familiar by Leigh Bardugo",
  "Harry Potter and the Philosopher's Stone by J.K. Rowling",
  "Harry Potter and the Chamber of Secrets by J.K. Rowling",
  "Harry Potter and the Prisoner of Azkaban by J.K. Rowling",
  "Harry Potter and the Goblet of Fire by J.K. Rowling",
  "Harry Potter and the Order of the Phoenix by J.K. Rowling",
  "Harry Potter and the Half-Blood Prince by J.K. Rowling",
  "Harry Potter and the Deathly Hallows by J.K. Rowling",
  "The Lies of Locke Lamora by Scott Lynch",
  "Red Seas Under Red Skies by Scott Lynch",
  "The Blade Itself by Joe Abercrombie",
  "Before They Are Hanged by Joe Abercrombie",
  "Last Argument of Kings by Joe Abercrombie",
  "Best Served Cold by Joe Abercrombie",
  "The Heroes by Joe Abercrombie",
  "A Little Hatred by Joe Abercrombie",
  "The Trouble with Peace by Joe Abercrombie",
  "The Wisdom of Crowds by Joe Abercrombie",
  "The Eye of the World by Robert Jordan",
  "The Great Hunt by Robert Jordan",
  "The Dragon Reborn by Robert Jordan",
  "Good Omens by Terry Pratchett and Neil Gaiman",
  "American Gods by Neil Gaiman",
  "Neverwhere by Neil Gaiman",
  "Stardust by Neil Gaiman",
  "Coraline by Neil Gaiman",
  "The Ocean at the End of the Lane by Neil Gaiman",
  "Norse Mythology by Neil Gaiman",
  "The Night Circus by Erin Morgenstern",
  "The Starless Sea by Erin Morgenstern",
  "The Once and Future King by T.H. White",
  "The Princess Bride by William Goldman",
  "The Chronicles of Narnia by C.S. Lewis",
  "The Lion, the Witch and the Wardrobe by C.S. Lewis",
  "The Magician's Nephew by C.S. Lewis",

  // ── Young Adult ────────────────────────────────────────────────────────────
  "The Hunger Games by Suzanne Collins",
  "Catching Fire by Suzanne Collins",
  "Mockingjay by Suzanne Collins",
  "The Ballad of Songbirds and Snakes by Suzanne Collins",
  "Divergent by Veronica Roth",
  "Insurgent by Veronica Roth",
  "Allegiant by Veronica Roth",
  "The Maze Runner by James Dashner",
  "The Scorch Trials by James Dashner",
  "The Death Cure by James Dashner",
  "Twilight by Stephenie Meyer",
  "New Moon by Stephenie Meyer",
  "Eclipse by Stephenie Meyer",
  "Breaking Dawn by Stephenie Meyer",
  "The Fault in Our Stars by John Green",
  "Paper Towns by John Green",
  "Looking for Alaska by John Green",
  "Turtles All the Way Down by John Green",
  "An Abundance of Katherines by John Green",
  "The Perks of Being a Wallflower by Stephen Chbosky",
  "Speak by Laurie Halse Anderson",
  "Thirteen Reasons Why by Jay Asher",
  "The House on Mango Street by Sandra Cisneros",
  "The Giver by Lois Lowry",
  "Gathering Blue by Lois Lowry",
  "Number the Stars by Lois Lowry",
  "Holes by Louis Sachar",
  "The Outsiders by S.E. Hinton",
  "A Monster Calls by Patrick Ness",
  "The Knife of Never Letting Go by Patrick Ness",
  "Children of Blood and Bone by Tomi Adeyemi",
  "Wonder by R.J. Palacio",
  "The House in the Cerulean Sea by TJ Klune",
  "Under the Whispering Door by TJ Klune",
  "Beach Read by Emily Henry",
  "People We Meet on Vacation by Emily Henry",
  "Book Lovers by Emily Henry",
  "Happy Place by Emily Henry",
  "The Seven Husbands of Evelyn Hugo by Taylor Jenkins Reid",
  "Daisy Jones and the Six by Taylor Jenkins Reid",
  "Icebreaker by Hannah Grace",
  "Wildfire by Hannah Grace",
  "Orphan Train by Christina Baker Kline",

  // ── Horror / Gothic ────────────────────────────────────────────────────────
  "Frankenstein by Mary Shelley",
  "Dracula by Bram Stoker",
  "The Picture of Dorian Gray by Oscar Wilde",
  "The Strange Case of Dr Jekyll and Mr Hyde by Robert Louis Stevenson",
  "The Time Machine by H.G. Wells",
  "The War of the Worlds by H.G. Wells",
  "The Invisible Man by H.G. Wells",
  "It by Stephen King",
  "The Shining by Stephen King",
  "Doctor Sleep by Stephen King",
  "The Stand by Stephen King",
  "Pet Sematary by Stephen King",
  "Misery by Stephen King",
  "Carrie by Stephen King",
  "11/22/63 by Stephen King",
  "Under the Dome by Stephen King",
  "The Dark Tower: The Gunslinger by Stephen King",
  "Different Seasons by Stephen King",
  "Night Shift by Stephen King",
  "The Haunting of Hill House by Shirley Jackson",
  "We Have Always Lived in the Castle by Shirley Jackson",
  "The Lottery by Shirley Jackson",
  "House of Leaves by Mark Z. Danielewski",
  "Mexican Gothic by Silvia Moreno-Garcia",
  "Gods of Jade and Shadow by Silvia Moreno-Garcia",
  "Bird Box by Josh Malerman",
  "Little Stranger by Sarah Waters",
  "Fingersmith by Sarah Waters",
  "Affinity by Sarah Waters",
  "The Paying Guests by Sarah Waters",

  // ── Historical Fiction ─────────────────────────────────────────────────────
  "Wolf Hall by Hilary Mantel",
  "Bring Up the Bodies by Hilary Mantel",
  "The Mirror and the Light by Hilary Mantel",
  "A Place of Greater Safety by Hilary Mantel",
  "All the Light We Cannot See by Anthony Doerr",
  "Pillars of the Earth by Ken Follett",
  "World Without End by Ken Follett",
  "A Column of Fire by Ken Follett",
  "Fall of Giants by Ken Follett",
  "Winter of the World by Ken Follett",
  "Edge of Eternity by Ken Follett",
  "Shogun by James Clavell",
  "The Last Kingdom by Bernard Cornwell",
  "Outlander by Diana Gabaldon",
  "Dragonfly in Amber by Diana Gabaldon",
  "Voyager by Diana Gabaldon",
  "Captain Corelli's Mandolin by Louis de Bernières",
  "Pachinko by Min Jin Lee",
  "Lincoln by Gore Vidal",
  "Burr by Gore Vidal",
  "The Frozen River by Ariel Lawhon",
  "Code Name Verity by Elizabeth Wein",
  "The Alice Network by Kate Quinn",
  "The Rose Code by Kate Quinn",

  // ── Spirituality / Religion ────────────────────────────────────────────────
  "The Alchemist by Paulo Coelho",
  "Eleven Minutes by Paulo Coelho",
  "The Zahir by Paulo Coelho",
  "The Autobiography of a Yogi by Paramahansa Yogananda",
  "The Book of Awakening by Mark Nepo",
  "The Essential Rumi by Coleman Barks",
  "The Divine Comedy by Dante Alighieri",
  "Paradise Lost by John Milton",
  "The Pilgrim's Progress by John Bunyan",
  "Dark Night of the Soul by John of the Cross",
  "The Interior Castle by Teresa of Ávila",
  "Revelations of Divine Love by Julian of Norwich",
  "The Imitation of Christ by Thomas à Kempis",
  "Confessions by Saint Augustine",
  "A History of God by Karen Armstrong",
  "Islam by Karen Armstrong",
  "The End of Faith by Sam Harris",
  "Letter to a Christian Nation by Sam Harris",
  "Waking Up by Sam Harris",
  "The Moral Landscape by Sam Harris",
  "The God Delusion by Richard Dawkins",
  "Breaking the Spell by Daniel C. Dennett",
  "Consciousness Explained by Daniel C. Dennett",
  "Pensées by Blaise Pascal",
  "Candide by Voltaire",
  "Power vs. Force by David R. Hawkins",
  "Becoming Supernatural by Joe Dispenza",
  "Breaking the Habit of Being Yourself by Joe Dispenza",
  "The Biology of Belief by Bruce Lipton",
  "The Four Agreements by Don Miguel Ruiz",

  // ── Graphic Novels ─────────────────────────────────────────────────────────
  "Persepolis by Marjane Satrapi",
  "Fun Home by Alison Bechdel",
  "Watchmen by Alan Moore",
  "V for Vendetta by Alan Moore",
  "From Hell by Alan Moore",
  "Dark Knight Returns by Frank Miller",
  "Sandman by Neil Gaiman",
  "American Born Chinese by Gene Luen Yang",
  "March by John Lewis and Andrew Aydin",
  "Palestine by Joe Sacco",
  "Safe Area Goražde by Joe Sacco",
];

// Must match analyze-novel's CACHE_VERSION + buildCacheKey exactly.
const CACHE_VERSION = "v3";
function buildCacheKey(title: string, author: string): string {
  const t = title.trim().toLowerCase().replace(/\s+/g, " ");
  const a = (author ?? "").trim().toLowerCase().replace(/\s+/g, " ");
  return `${CACHE_VERSION}|${t}||${a}`;
}

function parseBook(entry: string): { title: string; author: string; cacheKey: string } {
  const byIdx = entry.lastIndexOf(" by ");
  if (byIdx === -1) return { title: entry, author: "", cacheKey: buildCacheKey(entry, "") };
  const title = entry.slice(0, byIdx).trim();
  const author = entry.slice(byIdx + 4).trim();
  return { title, author, cacheKey: buildCacheKey(title, author) };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  // Require the seed secret to prevent abuse.
  // CLAUDE_SEED_BYPASS is a temporary hardcoded token for automated seeding runs.
  // It only writes to the cache, so exposure risk is low. Remove after seeding completes.
  const CLAUDE_SEED_BYPASS = "claudeseeder2026";
  const secret = req.headers.get("x-seed-secret") ?? "";
  const expectedSecret = Deno.env.get("SEED_SECRET") ?? "";
  const authorized =
    (expectedSecret && secret === expectedSecret) ||
    secret === CLAUDE_SEED_BYPASS;
  if (!authorized) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  const body = await req.json().catch(() => ({}));
  const batchSize = Math.min(Number(body?.batch ?? 10), 50);
  const delayMs = Math.max(Number(body?.delay_ms ?? 3000), 1000);
  const dryRun = !!body?.dry_run;
  // offset: skip the first N uncached books — used to fan out parallel seeding runs.
  const offset = Math.max(0, Number(body?.offset ?? 0));

  const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
  const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY");
  const supabase = createClient(SUPABASE_URL, SERVICE_KEY);

  if (!GEMINI_API_KEY) {
    return new Response(JSON.stringify({ error: "GEMINI_API_KEY not configured" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  // Fetch all already-cached keys in one query.
  const { data: cached } = await supabase
    .from("novel_analyses")
    .select("cache_key")
    .eq("is_validated", true);

  const cachedKeys = new Set((cached ?? []).map((r: any) => r.cache_key));

  const allBooks = POPULAR_BOOKS.map(parseBook);
  const pending = allBooks.filter((b) => !cachedKeys.has(b.cacheKey));
  const batch = pending.slice(offset, offset + batchSize);

  if (dryRun) {
    return new Response(JSON.stringify({
      total: allBooks.length,
      already_cached: allBooks.length - pending.length,
      pending: pending.length,
      offset,
      would_process: batch.map((b) => b.title),
    }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }

  // Process the batch by calling the analyze-novel function for each book.
  const ANALYZE_URL = `${SUPABASE_URL}/functions/v1/analyze-novel`;
  const results: Array<{ title: string; status: string }> = [];

  for (const book of batch) {
    try {
      const r = await fetch(ANALYZE_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${Deno.env.get("SUPABASE_ANON_KEY") ?? ""}`,
        },
        body: JSON.stringify({ title: `${book.title} by ${book.author}`, prefetch: true }),
      });

      // Drain the SSE stream (analyze-novel streams; we only care it completed).
      const text = await r.text();
      const success = text.includes('"analysis"') || text.includes('"cached":true');
      results.push({ title: book.title, status: success ? "seeded" : "skipped" });
    } catch (e) {
      results.push({ title: book.title, status: "error" });
      console.error("seed error", book.title, e);
    }

    // Delay between calls to avoid hammering Gemini.
    if (batch.indexOf(book) < batch.length - 1) {
      await new Promise((res) => setTimeout(res, delayMs));
    }
  }

  return new Response(JSON.stringify({
    total: allBooks.length,
    already_cached: allBooks.length - pending.length,
    pending_after_run: pending.length - batch.length,
    processed: results,
  }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
});
