-- Backfill canon_books with editorial canon (classic.ts + must-read.ts) titles
-- that were missing entirely, found by a full audit comparing both lists
-- against canon_books (350 rows -> was covering only 130/268 curated titles).
-- Without this, search_canon's fuzzy/trigram matching couldn't boost a typo'd
-- or hard-to-rank search for over half of NovelViz's own curated Classics/
-- Must-Reads -- directly undermines the "search bar needs to be impeccable,
-- starting with the Classics" project mission. Also includes ~11 high-value
-- akas (genuinely distinct strings: translated/retitled editions) where the
-- primary title alone wouldn't fuzzy-match a reader typing the alternate name.
INSERT INTO public.canon_books (title, author, source) VALUES
('Lysistrata', 'Aristophanes', 'daily_agent_canon_backfill_2026_07_18'),
('The Ramayana', 'Valmiki', 'daily_agent_canon_backfill_2026_07_18'),
('The Mahabharata', 'Vyasa', 'daily_agent_canon_backfill_2026_07_18'),
('Shakuntala', 'Kalidasa', 'daily_agent_canon_backfill_2026_07_18'),
('The Shahnameh', 'Ferdowsi', 'daily_agent_canon_backfill_2026_07_18'),
('The Tale of the Heike', 'Anonymous', 'daily_agent_canon_backfill_2026_07_18'),
('Romance of the Three Kingdoms', 'Luo Guanzhong', 'daily_agent_canon_backfill_2026_07_18'),
('Journey to the West', 'Wu Cheng''en', 'daily_agent_canon_backfill_2026_07_18'),
('Water Margin', 'Shi Nai''an', 'daily_agent_canon_backfill_2026_07_18'),
('Njal''s Saga', 'Anonymous', 'daily_agent_canon_backfill_2026_07_18'),
('The Decameron', 'Giovanni Boccaccio', 'daily_agent_canon_backfill_2026_07_18'),
('Orlando Furioso', 'Ludovico Ariosto', 'daily_agent_canon_backfill_2026_07_18'),
('The Lusiads', 'Luís de Camões', 'daily_agent_canon_backfill_2026_07_18'),
('The Faerie Queene', 'Edmund Spenser', 'daily_agent_canon_backfill_2026_07_18'),
('Tartuffe', 'Molière', 'daily_agent_canon_backfill_2026_07_18'),
('The Pilgrim''s Progress', 'John Bunyan', 'daily_agent_canon_backfill_2026_07_18'),
('Robinson Crusoe', 'Daniel Defoe', 'daily_agent_canon_backfill_2026_07_18'),
('Tom Jones', 'Henry Fielding', 'daily_agent_canon_backfill_2026_07_18'),
('Tristram Shandy', 'Laurence Sterne', 'daily_agent_canon_backfill_2026_07_18'),
('Dangerous Liaisons', 'Pierre Choderlos de Laclos', 'daily_agent_canon_backfill_2026_07_18'),
('Vanity Fair', 'William Makepeace Thackeray', 'daily_agent_canon_backfill_2026_07_18'),
('Barchester Towers', 'Anthony Trollope', 'daily_agent_canon_backfill_2026_07_18'),
('Oblomov', 'Ivan Goncharov', 'daily_agent_canon_backfill_2026_07_18'),
('A Hero of Our Time', 'Mikhail Lermontov', 'daily_agent_canon_backfill_2026_07_18'),
('The Scarlet Letter', 'Nathaniel Hawthorne', 'daily_agent_canon_backfill_2026_07_18'),
('My Ántonia', 'Willa Cather', 'daily_agent_canon_backfill_2026_07_18'),
('The Age of Innocence', 'Edith Wharton', 'daily_agent_canon_backfill_2026_07_18'),
('The Red Badge of Courage', 'Stephen Crane', 'daily_agent_canon_backfill_2026_07_18'),
('Sister Carrie', 'Theodore Dreiser', 'daily_agent_canon_backfill_2026_07_18'),
('The Awakening', 'Kate Chopin', 'daily_agent_canon_backfill_2026_07_18'),
('Dom Casmurro', 'Machado de Assis', 'daily_agent_canon_backfill_2026_07_18'),
('Strange Case of Dr Jekyll and Mr Hyde', 'Robert Louis Stevenson', 'daily_agent_canon_backfill_2026_07_18'),
('The Woman in White', 'Wilkie Collins', 'daily_agent_canon_backfill_2026_07_18'),
('A Doll''s House', 'Henrik Ibsen', 'daily_agent_canon_backfill_2026_07_18'),
('The Cherry Orchard', 'Anton Chekhov', 'daily_agent_canon_backfill_2026_07_18'),
('The Good Soldier', 'Ford Madox Ford', 'daily_agent_canon_backfill_2026_07_18'),
('Sons and Lovers', 'D.H. Lawrence', 'daily_agent_canon_backfill_2026_07_18'),
('A Passage to India', 'E.M. Forster', 'daily_agent_canon_backfill_2026_07_18'),
('Brideshead Revisited', 'Evelyn Waugh', 'daily_agent_canon_backfill_2026_07_18'),
('The Good Soldier Švejk', 'Jaroslav Hašek', 'daily_agent_canon_backfill_2026_07_18'),
('Berlin Alexanderplatz', 'Alfred Döblin', 'daily_agent_canon_backfill_2026_07_18'),
('As I Lay Dying', 'William Faulkner', 'daily_agent_canon_backfill_2026_07_18'),
('The Sun Also Rises', 'Ernest Hemingway', 'daily_agent_canon_backfill_2026_07_18'),
('Journey to the End of the Night', 'Louis-Ferdinand Céline', 'daily_agent_canon_backfill_2026_07_18'),
('The Tin Drum', 'Günter Grass', 'daily_agent_canon_backfill_2026_07_18'),
('Independent People', 'Halldór Laxness', 'daily_agent_canon_backfill_2026_07_18'),
('Voss', 'Patrick White', 'daily_agent_canon_backfill_2026_07_18'),
('Hunger', 'Knut Hamsun', 'daily_agent_canon_backfill_2026_07_18'),
('Wide Sargasso Sea', 'Jean Rhys', 'daily_agent_canon_backfill_2026_07_18'),
('A House for Mr Biswas', 'V.S. Naipaul', 'daily_agent_canon_backfill_2026_07_18'),
('The Unbearable Lightness of Being', 'Milan Kundera', 'daily_agent_canon_backfill_2026_07_18'),
('Austerlitz', 'W.G. Sebald', 'daily_agent_canon_backfill_2026_07_18'),
('Never Let Me Go', 'Kazuo Ishiguro', 'daily_agent_canon_backfill_2026_07_18'),
('Suite Française', 'Irène Némirovsky', 'daily_agent_canon_backfill_2026_07_18'),
('Life and Fate', 'Vasily Grossman', 'daily_agent_canon_backfill_2026_07_18'),
('One Day in the Life of Ivan Denisovich', 'Aleksandr Solzhenitsyn', 'daily_agent_canon_backfill_2026_07_18'),
('We', 'Yevgeny Zamyatin', 'daily_agent_canon_backfill_2026_07_18'),
('Song of Solomon', 'Toni Morrison', 'daily_agent_canon_backfill_2026_07_18'),
('The Color Purple', 'Alice Walker', 'daily_agent_canon_backfill_2026_07_18'),
('Gilead', 'Marilynne Robinson', 'daily_agent_canon_backfill_2026_07_18'),
('Lonesome Dove', 'Larry McMurtry', 'daily_agent_canon_backfill_2026_07_18'),
('All the King''s Men', 'Robert Penn Warren', 'daily_agent_canon_backfill_2026_07_18'),
('The Adventures of Augie March', 'Saul Bellow', 'daily_agent_canon_backfill_2026_07_18'),
('The Left Hand of Darkness', 'Ursula K. Le Guin', 'daily_agent_canon_backfill_2026_07_18'),
('Neuromancer', 'William Gibson', 'daily_agent_canon_backfill_2026_07_18'),
('2666', 'Roberto Bolaño', 'daily_agent_canon_backfill_2026_07_18'),
('The Death of Artemio Cruz', 'Carlos Fuentes', 'daily_agent_canon_backfill_2026_07_18'),
('The Feast of the Goat', 'Mario Vargas Llosa', 'daily_agent_canon_backfill_2026_07_18'),
('Kristin Lavransdatter', 'Sigrid Undset', 'daily_agent_canon_backfill_2026_07_18'),
('The Palm-Wine Drinkard', 'Amos Tutuola', 'daily_agent_canon_backfill_2026_07_18'),
('Season of Migration to the North', 'Tayeb Salih', 'daily_agent_canon_backfill_2026_07_18'),
('Cry, the Beloved Country', 'Alan Paton', 'daily_agent_canon_backfill_2026_07_18'),
('July''s People', 'Nadine Gordimer', 'daily_agent_canon_backfill_2026_07_18'),
('Petals of Blood', 'Ngũgĩ wa Thiong''o', 'daily_agent_canon_backfill_2026_07_18'),
('The Wind-Up Bird Chronicle', 'Haruki Murakami', 'daily_agent_canon_backfill_2026_07_18'),
('Silence', 'Shūsaku Endō', 'daily_agent_canon_backfill_2026_07_18'),
('The Makioka Sisters', 'Jun''ichirō Tanizaki', 'daily_agent_canon_backfill_2026_07_18'),
('Rashomon and Other Stories', 'Ryūnosuke Akutagawa', 'daily_agent_canon_backfill_2026_07_18'),
('Palace Walk', 'Naguib Mahfouz', 'daily_agent_canon_backfill_2026_07_18'),
('The God of Small Things', 'Arundhati Roy', 'daily_agent_canon_backfill_2026_07_18'),
('A Suitable Boy', 'Vikram Seth', 'daily_agent_canon_backfill_2026_07_18'),
('Untouchable', 'Mulk Raj Anand', 'daily_agent_canon_backfill_2026_07_18'),
('Lucky Jim', 'Kingsley Amis', 'daily_agent_canon_backfill_2026_07_18'),
('The History of the Peloponnesian War', 'Thucydides', 'daily_agent_canon_backfill_2026_07_18'),
('The Annals', 'Tacitus', 'daily_agent_canon_backfill_2026_07_18'),
('The Muqaddimah', 'Ibn Khaldun', 'daily_agent_canon_backfill_2026_07_18'),
('Symposium', 'Plato', 'daily_agent_canon_backfill_2026_07_18'),
('On the Nature of Things', 'Lucretius', 'daily_agent_canon_backfill_2026_07_18'),
('Confessions', 'Saint Augustine', 'daily_agent_canon_backfill_2026_07_18'),
('The Consolation of Philosophy', 'Boethius', 'daily_agent_canon_backfill_2026_07_18'),
('Discourse on Method', 'René Descartes', 'daily_agent_canon_backfill_2026_07_18'),
('An Enquiry Concerning Human Understanding', 'David Hume', 'daily_agent_canon_backfill_2026_07_18'),
('Two Treatises of Government', 'John Locke', 'daily_agent_canon_backfill_2026_07_18'),
('A Vindication of the Rights of Woman', 'Mary Wollstonecraft', 'daily_agent_canon_backfill_2026_07_18'),
('The Federalist Papers', 'Alexander Hamilton', 'daily_agent_canon_backfill_2026_07_18'),
('Phenomenology of Spirit', 'G.W.F. Hegel', 'daily_agent_canon_backfill_2026_07_18'),
('On the Genealogy of Morals', 'Friedrich Nietzsche', 'daily_agent_canon_backfill_2026_07_18'),
('On War', 'Carl von Clausewitz', 'daily_agent_canon_backfill_2026_07_18'),
('On Liberty', 'John Stuart Mill', 'daily_agent_canon_backfill_2026_07_18'),
('The Interpretation of Dreams', 'Sigmund Freud', 'daily_agent_canon_backfill_2026_07_18'),
('The Varieties of Religious Experience', 'William James', 'daily_agent_canon_backfill_2026_07_18'),
('The Protestant Ethic and the Spirit of Capitalism', 'Max Weber', 'daily_agent_canon_backfill_2026_07_18'),
('Suicide', 'Émile Durkheim', 'daily_agent_canon_backfill_2026_07_18'),
('The Souls of Black Folk', 'W.E.B. Du Bois', 'daily_agent_canon_backfill_2026_07_18'),
('Being and Nothingness', 'Jean-Paul Sartre', 'daily_agent_canon_backfill_2026_07_18'),
('Philosophical Investigations', 'Ludwig Wittgenstein', 'daily_agent_canon_backfill_2026_07_18'),
('The Origins of Totalitarianism', 'Hannah Arendt', 'daily_agent_canon_backfill_2026_07_18'),
('Notes of a Native Son', 'James Baldwin', 'daily_agent_canon_backfill_2026_07_18'),
('The Autobiography of Benjamin Franklin', 'Benjamin Franklin', 'daily_agent_canon_backfill_2026_07_18'),
('Walden', 'Henry David Thoreau', 'daily_agent_canon_backfill_2026_07_18'),
('Narrative of the Life of Frederick Douglass', 'Frederick Douglass', 'daily_agent_canon_backfill_2026_07_18'),
('Long Walk to Freedom', 'Nelson Mandela', 'daily_agent_canon_backfill_2026_07_18'),
('The Decline and Fall of the Roman Empire', 'Edward Gibbon', 'daily_agent_canon_backfill_2026_07_18'),
('Democracy and Education', 'John Dewey', 'daily_agent_canon_backfill_2026_07_18'),
('The Wretched of the Earth', 'Frantz Fanon', 'daily_agent_canon_backfill_2026_07_18'),
('Orientalism', 'Edward Said', 'daily_agent_canon_backfill_2026_07_18'),
('The Feminine Mystique', 'Betty Friedan', 'daily_agent_canon_backfill_2026_07_18'),
('Silent Spring', 'Rachel Carson', 'daily_agent_canon_backfill_2026_07_18'),
('Discipline and Punish', 'Michel Foucault', 'daily_agent_canon_backfill_2026_07_18'),
('The Double Helix', 'James D. Watson', 'daily_agent_canon_backfill_2026_07_18'),
('Chaos: Making a New Science', 'James Gleick', 'daily_agent_canon_backfill_2026_07_18'),
('The Guns of August', 'Barbara Tuchman', 'daily_agent_canon_backfill_2026_07_18'),
('The Rise and Fall of the Third Reich', 'William L. Shirer', 'daily_agent_canon_backfill_2026_07_18'),
('The General Theory of Employment, Interest and Money', 'John Maynard Keynes', 'daily_agent_canon_backfill_2026_07_18'),
('The Road to Serfdom', 'Friedrich Hayek', 'daily_agent_canon_backfill_2026_07_18'),
('The Bhagavad Gita', 'Vyasa', 'daily_agent_canon_backfill_2026_07_18'),
('Gulliver''s Travels', 'Jonathan Swift', 'daily_agent_canon_backfill_2026_07_18'),
('Heart of Darkness', 'Joseph Conrad', 'daily_agent_canon_backfill_2026_07_18'),
('The Radetzky March', 'Joseph Roth', 'daily_agent_canon_backfill_2026_07_18'),
('Invisible Man', 'Ralph Ellison', 'daily_agent_canon_backfill_2026_07_18'),
('Pedro Páramo', 'Juan Rulfo', 'daily_agent_canon_backfill_2026_07_18'),
('Snow Country', 'Yasunari Kawabata', 'daily_agent_canon_backfill_2026_07_18'),
('Disgrace', 'J.M. Coetzee', 'daily_agent_canon_backfill_2026_07_18'),
('Essays', 'Michel de Montaigne', 'daily_agent_canon_backfill_2026_07_18'),
('Democracy in America', 'Alexis de Tocqueville', 'daily_agent_canon_backfill_2026_07_18'),
('A Room of One''s Own', 'Virginia Woolf', 'daily_agent_canon_backfill_2026_07_18'),
('The Second Sex', 'Simone de Beauvoir', 'daily_agent_canon_backfill_2026_07_18'),
('The Fire Next Time', 'James Baldwin', 'daily_agent_canon_backfill_2026_07_18'),
('The Impostor', 'Molière', 'daily_agent_canon_backfill_2026_07_18'),
('The History of Tom Jones, a Foundling', 'Henry Fielding', 'daily_agent_canon_backfill_2026_07_18'),
('The Life and Opinions of Tristram Shandy, Gentleman', 'Laurence Sterne', 'daily_agent_canon_backfill_2026_07_18'),
('Les Liaisons Dangereuses', 'Pierre Choderlos de Laclos', 'daily_agent_canon_backfill_2026_07_18'),
('Dr. Jekyll and Mr. Hyde', 'Robert Louis Stevenson', 'daily_agent_canon_backfill_2026_07_18'),
('Rashomon', 'Ryūnosuke Akutagawa', 'daily_agent_canon_backfill_2026_07_18'),
('Prolegomena', 'Ibn Khaldun', 'daily_agent_canon_backfill_2026_07_18'),
('De Rerum Natura', 'Lucretius', 'daily_agent_canon_backfill_2026_07_18'),
('The Federalist', 'Alexander Hamilton', 'daily_agent_canon_backfill_2026_07_18'),
('Vom Kriege', 'Carl von Clausewitz', 'daily_agent_canon_backfill_2026_07_18'),
('Chaos', 'James Gleick', 'daily_agent_canon_backfill_2026_07_18');
