-- 2026-09-20 (daily_novel_viz_feat scheduled task).
--
-- New automated check this session added (src/test/canon-coverage.test.ts)
-- cross-references every classic.ts/must-read.ts title against every
-- canon_books-touching migration -- the fix both the 2026-09-19
-- backend_audit and its daily_backend companion session independently
-- recommended, after rounds 85-92 quietly went 8 rounds without a
-- canon_books backfill before being caught. Running it for the first time
-- surfaced a much larger, older version of the same gap: 62 classic.ts
-- entries and 6 must-read.ts entries -- some pre-dating the canon_books
-- table itself (created 2026-07-17), most from classic.ts's much longer
-- history never having been retroactively backfilled the way the July
-- "classics_tier" seed and later per-round backfills covered -- have never
-- had a canon_books row under any spelling. These are famous, unambiguous
-- works (A Brief History of Time, The Selfish Gene, Uncle Tom's Cabin,
-- Being and Time among them), not obscure specialist picks: exactly the
-- titles this app's "as many books as possible, Classics first" brief cares
-- about most, and exactly the ones a user is most likely to type into the
-- search bar and expect canon-injected typo tolerance / ranking for.
--
-- Every (title, author) pair below is copied verbatim from classic.ts /
-- must-read.ts (via the same normalizeForSearch the app itself uses),
-- generated by the new test's own extraction logic rather than re-typed by
-- hand, to guarantee zero transcription drift between the source list and
-- this migration. ON CONFLICT DO NOTHING / WHERE NOT EXISTS guards, same
-- pattern as every prior canon_books insert since 2026-07-17 -- safe to
-- re-run, cannot collide with or duplicate any existing row.
--
-- Deliberately not a curation round (no new titles added to classic.ts /
-- must-read.ts today, no new "why" annotations) -- this is closing an
-- existing-content coverage gap, the same category of fix as the
-- rounds85_92 backfill, just larger and caught by an automated check
-- instead of a manual spot-check this time.

insert into canon_books (title, author, source) values
  ('The Man Without Qualities', 'Robert Musil', 'classic_daily_curation_backfill_2026_09_20'),
  ('Tender Is the Night', 'F. Scott Fitzgerald', 'classic_daily_curation_backfill_2026_09_20'),
  ('Billiards at Half-Past Nine', 'Heinrich Böll', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Remains of the Day', 'Kazuo Ishiguro', 'classic_daily_curation_backfill_2026_09_20'),
  ('A Confederacy of Dunces', 'John Kennedy Toole', 'classic_daily_curation_backfill_2026_09_20'),
  ('American Pastoral', 'Philip Roth', 'classic_daily_curation_backfill_2026_09_20'),
  ('Rabbit, Run', 'John Updike', 'classic_daily_curation_backfill_2026_09_20'),
  ('White Noise', 'Don DeLillo', 'classic_daily_curation_backfill_2026_09_20'),
  ('Solaris', 'Stanisław Lem', 'classic_daily_curation_backfill_2026_09_20'),
  ('Hopscotch', 'Julio Cortázar', 'classic_daily_curation_backfill_2026_09_20'),
  ('The House of the Spirits', 'Isabel Allende', 'classic_daily_curation_backfill_2026_09_20'),
  ('A Personal Matter', 'Kenzaburō Ōe', 'classic_daily_curation_backfill_2026_09_20'),
  ('House Made of Dawn', 'N. Scott Momaday', 'classic_daily_curation_backfill_2026_09_20'),
  ('Being and Time', 'Martin Heidegger', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Selfish Gene', 'Richard Dawkins', 'classic_daily_curation_backfill_2026_09_20'),
  ('A Brief History of Time', 'Stephen Hawking', 'classic_daily_curation_backfill_2026_09_20'),
  ('Capital in the Twenty-First Century', 'Thomas Piketty', 'classic_daily_curation_backfill_2026_09_20'),
  ('Mother Courage and Her Children', 'Bertolt Brecht', 'classic_daily_curation_backfill_2026_09_20'),
  ('The World as Will and Representation', 'Arthur Schopenhauer', 'classic_daily_curation_backfill_2026_09_20'),
  ('A History of Western Philosophy', 'Bertrand Russell', 'classic_daily_curation_backfill_2026_09_20'),
  ('Uncle Vanya', 'Anton Chekhov', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Labyrinth of Solitude', 'Octavio Paz', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Guide for the Perplexed', 'Maimonides', 'classic_daily_curation_backfill_2026_09_20'),
  ('Phèdre', 'Jean Racine', 'classic_daily_curation_backfill_2026_09_20'),
  ('Gravity and Grace', 'Simone Weil', 'classic_daily_curation_backfill_2026_09_20'),
  ('Notebook of a Return to the Native Land', 'Aimé Césaire', 'classic_daily_curation_backfill_2026_09_20'),
  ('Up From Slavery', 'Booker T. Washington', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Institutes of Justinian', 'Justinian I', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Hippocratic Corpus', 'Hippocrates', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Kumulipo', 'Anonymous', 'classic_daily_curation_backfill_2026_09_20'),
  ('Khamsa', 'Alisher Navoi', 'classic_daily_curation_backfill_2026_09_20'),
  ('Theory of Games and Economic Behavior', 'John von Neumann and Oskar Morgenstern', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Song of Roland', 'Anonymous', 'classic_daily_curation_backfill_2026_09_20'),
  ('Cantar de Mio Cid', 'Anonymous', 'classic_daily_curation_backfill_2026_09_20'),
  ('On the Fabric of the Human Body', 'Andreas Vesalius', 'classic_daily_curation_backfill_2026_09_20'),
  ('Elements of Chemistry', 'Antoine Lavoisier', 'classic_daily_curation_backfill_2026_09_20'),
  ('Experiments on Plant Hybridization', 'Gregor Mendel', 'classic_daily_curation_backfill_2026_09_20'),
  ('Le Morte d''Arthur', 'Thomas Malory', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Nibelungenlied', 'Anonymous', 'classic_daily_curation_backfill_2026_09_20'),
  ('Uncle Tom''s Cabin', 'Harriet Beecher Stowe', 'classic_daily_curation_backfill_2026_09_20'),
  ('So Long a Letter', 'Mariama Bâ', 'classic_daily_curation_backfill_2026_09_20'),
  ('Hedda Gabler', 'Henrik Ibsen', 'classic_daily_curation_backfill_2026_09_20'),
  ('Bartleby, the Scrivener', 'Herman Melville', 'classic_daily_curation_backfill_2026_09_20'),
  ('Utilitarianism', 'John Stuart Mill', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Conference of the Birds', 'Farid ud-Din Attar', 'classic_daily_curation_backfill_2026_09_20'),
  ('Lyrical Ballads', 'William Wordsworth and Samuel Taylor Coleridge', 'classic_daily_curation_backfill_2026_09_20'),
  ('Don Juan', 'Lord Byron', 'classic_daily_curation_backfill_2026_09_20'),
  ('QED: The Strange Theory of Light and Matter', 'Richard Feynman', 'classic_daily_curation_backfill_2026_09_20'),
  ('What Is Life?', 'Erwin Schrödinger', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Twelve Caesars', 'Suetonius', 'classic_daily_curation_backfill_2026_09_20'),
  ('Lamia, Isabella, The Eve of St. Agnes, and Other Poems', 'John Keats', 'classic_daily_curation_backfill_2026_09_20'),
  ('Prometheus Unbound', 'Percy Bysshe Shelley', 'classic_daily_curation_backfill_2026_09_20'),
  ('Han Feizi', 'Han Fei', 'classic_daily_curation_backfill_2026_09_20'),
  ('Arthashastra', 'Kautilya', 'classic_daily_curation_backfill_2026_09_20'),
  ('On the Motion of the Heart and Blood in Animals', 'William Harvey', 'classic_daily_curation_backfill_2026_09_20'),
  ('On Computable Numbers, with an Application to the Entscheidungsproblem', 'Alan Turing', 'classic_daily_curation_backfill_2026_09_20'),
  ('Half of a Yellow Sun', 'Chimamanda Ngozi Adichie', 'classic_daily_curation_backfill_2026_09_20'),
  ('Life of Pi', 'Yann Martel', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Principles of Chemistry', 'Dmitri Mendeleev', 'classic_daily_curation_backfill_2026_09_20'),
  ('The Physical Geography of the Sea', 'Matthew Fontaine Maury', 'classic_daily_curation_backfill_2026_09_20'),
  ('Geography', 'Ptolemy', 'classic_daily_curation_backfill_2026_09_20'),
  ('Analysis Situs', 'Henri Poincaré', 'classic_daily_curation_backfill_2026_09_20'),
  ('Their Eyes Were Watching God', 'Zora Neale Hurston', 'must_read_backfill_2026_09_20'),
  ('Pale Fire', 'Vladimir Nabokov', 'must_read_backfill_2026_09_20'),
  ('The Histories', 'Herodotus', 'must_read_backfill_2026_09_20'),
  ('Man''s Search for Meaning', 'Viktor E. Frankl', 'must_read_backfill_2026_09_20'),
  ('Gödel, Escher, Bach', 'Douglas Hofstadter', 'must_read_backfill_2026_09_20'),
  ('The Black Swan', 'Nassim Nicholas Taleb', 'must_read_backfill_2026_09_20')
on conflict ((lower(title)), (lower(author))) do nothing;

insert into seed_book_list (entry)
select v.entry
from (values
  ('The Man Without Qualities by Robert Musil'),
  ('Tender Is the Night by F. Scott Fitzgerald'),
  ('Billiards at Half-Past Nine by Heinrich Böll'),
  ('The Remains of the Day by Kazuo Ishiguro'),
  ('A Confederacy of Dunces by John Kennedy Toole'),
  ('American Pastoral by Philip Roth'),
  ('Rabbit, Run by John Updike'),
  ('White Noise by Don DeLillo'),
  ('Solaris by Stanisław Lem'),
  ('Hopscotch by Julio Cortázar'),
  ('The House of the Spirits by Isabel Allende'),
  ('A Personal Matter by Kenzaburō Ōe'),
  ('House Made of Dawn by N. Scott Momaday'),
  ('Being and Time by Martin Heidegger'),
  ('The Selfish Gene by Richard Dawkins'),
  ('A Brief History of Time by Stephen Hawking'),
  ('Capital in the Twenty-First Century by Thomas Piketty'),
  ('Mother Courage and Her Children by Bertolt Brecht'),
  ('The World as Will and Representation by Arthur Schopenhauer'),
  ('A History of Western Philosophy by Bertrand Russell'),
  ('Uncle Vanya by Anton Chekhov'),
  ('The Labyrinth of Solitude by Octavio Paz'),
  ('The Guide for the Perplexed by Maimonides'),
  ('Phèdre by Jean Racine'),
  ('Gravity and Grace by Simone Weil'),
  ('Notebook of a Return to the Native Land by Aimé Césaire'),
  ('Up From Slavery by Booker T. Washington'),
  ('The Institutes of Justinian by Justinian I'),
  ('The Hippocratic Corpus by Hippocrates'),
  ('The Kumulipo by Anonymous'),
  ('Khamsa by Alisher Navoi'),
  ('Theory of Games and Economic Behavior by John von Neumann and Oskar Morgenstern'),
  ('The Song of Roland by Anonymous'),
  ('Cantar de Mio Cid by Anonymous'),
  ('On the Fabric of the Human Body by Andreas Vesalius'),
  ('Elements of Chemistry by Antoine Lavoisier'),
  ('Experiments on Plant Hybridization by Gregor Mendel'),
  ('Le Morte d''Arthur by Thomas Malory'),
  ('The Nibelungenlied by Anonymous'),
  ('Uncle Tom''s Cabin by Harriet Beecher Stowe'),
  ('So Long a Letter by Mariama Bâ'),
  ('Hedda Gabler by Henrik Ibsen'),
  ('Bartleby, the Scrivener by Herman Melville'),
  ('Utilitarianism by John Stuart Mill'),
  ('The Conference of the Birds by Farid ud-Din Attar'),
  ('Lyrical Ballads by William Wordsworth and Samuel Taylor Coleridge'),
  ('Don Juan by Lord Byron'),
  ('QED: The Strange Theory of Light and Matter by Richard Feynman'),
  ('What Is Life? by Erwin Schrödinger'),
  ('The Twelve Caesars by Suetonius'),
  ('Lamia, Isabella, The Eve of St. Agnes, and Other Poems by John Keats'),
  ('Prometheus Unbound by Percy Bysshe Shelley'),
  ('Han Feizi by Han Fei'),
  ('Arthashastra by Kautilya'),
  ('On the Motion of the Heart and Blood in Animals by William Harvey'),
  ('On Computable Numbers, with an Application to the Entscheidungsproblem by Alan Turing'),
  ('Half of a Yellow Sun by Chimamanda Ngozi Adichie'),
  ('Life of Pi by Yann Martel'),
  ('The Principles of Chemistry by Dmitri Mendeleev'),
  ('The Physical Geography of the Sea by Matthew Fontaine Maury'),
  ('Geography by Ptolemy'),
  ('Analysis Situs by Henri Poincaré'),
  ('Their Eyes Were Watching God by Zora Neale Hurston'),
  ('Pale Fire by Vladimir Nabokov'),
  ('The Histories by Herodotus'),
  ('Man''s Search for Meaning by Viktor E. Frankl'),
  ('Gödel, Escher, Bach by Douglas Hofstadter'),
  ('The Black Swan by Nassim Nicholas Taleb')
) as v(entry)
where not exists (
  select 1 from seed_book_list s where lower(trim(s.entry)) = lower(trim(v.entry))
);
